### ISSUE TITLE
Missing libs for Generic x86_64

### ISSUE THREAD

**Issue by cooperdk** [bite-your-idols/Gamestarter#102]
Retroarch is not starting on X86_64

In: Gamestarter/repository.gamestarter/game.retroarch/lib-Gen-LE9/
There are missing libs:  libva.so.1, libva-drm.so.1, libva-x11.so.1

**Comment by bite-your-idols** [comment]
now you have them... 
trying to make it work for Gen devices using LE9:
https://forum.libreelec.tv/thread/287-gamestarter-retrogaming-add-ons-rpi-generic/?postID=100534#post100534
Please confirm me that it works

**Comment by bite-your-idols** [comment]
RetroArch 8.174.11 addon release fixed it.
