### ISSUE TITLE
Pcsx rearmed r22 - audio and video stuttering

### ISSUE THREAD

**Issue by AlexPaterson77** [bite-your-idols/Gamestarter#103]
I downloaded this core recently, it worked once with no issue. Played final fantasy 8 for some hours, restarted the raspberry pi 3 and it started stuttering.
I tried re installing retroarch and it's cores. Still the same behavior, the game works once and stops working correctly the second time. I did a soft reset of my kodi, re installed retroarch and its cores. Same behavior. 

Besides this, I'm unable to use retroarch save states with this core version. The previous version presented none of these issues.

**Comment by bite-your-idols** [comment]
Hola , 

Estaré fuera del estudio hasta el 15 de Octubre, para cualquier consulta puedes escribir a studio@onclick.es o ramon@onclick.es.

Un saludo ✌️

**Comment by bite-your-idols** [comment]
Is this core from Lakka zip package or manually downloaded from retroarch settings?

**Comment by AlexPaterson77** [comment]
I downloaded it directly from the addon settings.
I'm trying the previous version right now.

Simone

**Comment by AlexPaterson77** [comment]
Errata corridge.
I was using the core i downloaded directly from retroarch.

I uninstalled the addon.
Deleted all system directories.
Re installed the addon.
Downloaded the cores again.

Now it works.

Sorry for the inconvenience
Simone
