### ISSUE TITLE
mess2014

### ISSUE THREAD

**Issue by camatthew88** [bite-your-idols/Gamestarter#104]
mess2014 is needed for cdi emulation there isnt mess2014, the mess2014 core doesent work from core updater

**Comment by camatthew88** [comment]
see this
http://www.lakka.tv/doc/Packaging-a-libretro-core-for-Lakka/

**Comment by bite-your-idols** [comment]
Gamestarter RA addon uses both Lakka cores or Libretro's buildbot ones. If your desired core is not working or not included in those repos you can try to compile by yourself and share it with the community.
