### ISSUE TITLE
RetroArch crashes during startup

### ISSUE THREAD

**Issue by abxxxxx** [bite-your-idols/Gamestarter#105]
Dear all,

keen to try RetroArch, I installed LibreELEC 8.2.5 on the micro SD card of my WeTek Play 2. I added the Gamestarter repository and installed RetroArch. I tried the 8.175.12 first, then the 8.174.11 version. After beeing asked to leave Kodi, the RetroArch splash screen appears. After a couple of seconds it crashes and Kodi starts up again. Can anyone help me solve this issue? Find the logs below. Thank you very much in advance!

kodi.log:
`﻿17:44:02.817 T:548278820864  NOTICE: special://profile/ is mapped to: special://masterprofile/
17:44:02.817 T:548278820864  NOTICE: -----------------------------------------------------------------------
17:44:02.817 T:548278820864  NOTICE: Starting Kodi (17.6 Git:a9a7a20). Platform: Linux ARM 64-bit
17:44:02.817 T:548278820864  NOTICE: Using Release Kodi x64 build
17:44:02.818 T:548278820864  NOTICE: Kodi compiled Apr 13 2018 by GCC 6.2.0 for Linux ARM 64-bit version 3.14.29 (200221)
17:44:02.818 T:548278820864  NOTICE: Running on LibreELEC (official): 8.2.5, kernel: Linux ARM 64-bit version 3.14.29
17:44:02.818 T:548278820864  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
17:44:02.818 T:548278820864  NOTICE: Host CPU: AArch64 Processor rev 4 (aarch64), 4 cores available
17:44:02.818 T:548278820864  NOTICE: ARM Features: Neon disabled
17:44:02.818 T:548278820864  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi/
17:44:02.818 T:548278820864  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/kodi
17:44:02.818 T:548278820864  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/kodi/addons
17:44:02.818 T:548278820864  NOTICE: special://masterprofile/ is mapped to: /storage/.kodi/userdata
17:44:02.818 T:548278820864  NOTICE: special://envhome/ is mapped to: /storage
17:44:02.818 T:548278820864  NOTICE: special://home/ is mapped to: /storage/.kodi
17:44:02.818 T:548278820864  NOTICE: special://temp/ is mapped to: /storage/.kodi/temp
17:44:02.818 T:548278820864  NOTICE: special://logpath/ is mapped to: /storage/.kodi/temp
17:44:02.818 T:548278820864  NOTICE: The executable running is: /usr/lib/kodi/kodi.bin
17:44:02.818 T:548278820864  NOTICE: Local hostname: LibreELEC
17:44:02.818 T:548278820864  NOTICE: Log File is located: /storage/.kodi/temp//kodi.log
17:44:02.818 T:548278820864  NOTICE: -----------------------------------------------------------------------
17:44:02.836 T:548278820864   ERROR: DBus: Error org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
17:44:02.842 T:548278820864  NOTICE: load settings...
17:44:02.842 T:548278820864  NOTICE: AML device detected
17:44:02.927 T:548278820864  NOTICE: Found 2 Lists of Devices
17:44:02.927 T:548278820864  NOTICE: Enumerated ALSA devices:
17:44:02.927 T:548278820864  NOTICE:     Device 1
17:44:02.927 T:548278820864  NOTICE:         m_deviceName      : default
17:44:02.927 T:548278820864  NOTICE:         m_displayName     : Default (AML-M8AUDIO Analog)
17:44:02.927 T:548278820864  NOTICE:         m_displayNameExtra:
17:44:02.927 T:548278820864  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
17:44:02.927 T:548278820864  NOTICE:         m_channels        : FL,FR,UNKNOWN1,LFE,BL,BR,FC,BC,BLOC,BROC
17:44:02.927 T:548278820864  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
17:44:02.928 T:548278820864  NOTICE:         m_dataFormats     : AE_FMT_S32NE
17:44:02.928 T:548278820864  NOTICE:         m_streamTypes     : No passthrough capabilities
17:44:02.928 T:548278820864  NOTICE:     Device 2
17:44:02.928 T:548278820864  NOTICE:         m_deviceName      : hdmi:CARD=AMLM8AUDIO,DEV=0
17:44:02.928 T:548278820864  NOTICE:         m_displayName     : AML-M8AUDIO
17:44:02.928 T:548278820864  NOTICE:         m_displayNameExtra: HDMI
17:44:02.928 T:548278820864  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
17:44:02.928 T:548278820864  NOTICE:         m_channels        : FL,FR,BL,BR,FC,LFE,SL,SR
17:44:02.928 T:548278820864  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
17:44:02.928 T:548278820864  NOTICE:         m_dataFormats     : AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
17:44:02.928 T:548278820864  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
17:44:02.928 T:548278820864  NOTICE: Enumerated PULSE devices:
17:44:02.928 T:548278820864  NOTICE:     Device 1
17:44:02.928 T:548278820864  NOTICE:         m_deviceName      : Default
17:44:02.928 T:548278820864  NOTICE:         m_displayName     : Default
17:44:02.928 T:548278820864  NOTICE:         m_displayNameExtra: Bluetooth Audio (PULSEAUDIO)
17:44:02.928 T:548278820864  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
17:44:02.928 T:548278820864  NOTICE:         m_channels        : FL,FR
17:44:02.928 T:548278820864  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
17:44:02.928 T:548278820864  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
17:44:02.928 T:548278820864  NOTICE:         m_streamTypes     : No passthrough capabilities
17:44:02.938 T:548278820864  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml
17:44:02.938 T:548278820864  NOTICE: Contents of special://xbmc/system/advancedsettings.xml are...
                                            <?xml version="1.0" encoding="UTF-8" ?>
                                            <advancedsettings>
                                              <showexitbutton>false</showexitbutton>
                                              <remotedelay>1</remotedelay>
                                              <samba>
                                                <clienttimeout>30</clienttimeout>
                                              </samba>
                                            </advancedsettings>
17:44:02.939 T:548278820864  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
17:44:02.939 T:548278820864  NOTICE: Default Video Player: VideoPlayer
17:44:02.939 T:548278820864  NOTICE: Default Audio Player: paplayer
17:44:02.939 T:548278820864  NOTICE: Disabled debug logging due to GUI setting. Level 0.
17:44:02.939 T:548278820864  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
17:44:02.940 T:548278820864  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
17:44:02.940 T:548278820864  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
17:44:02.941 T:548278820864  NOTICE: Loaded playercorefactory configuration
17:44:02.941 T:548278820864  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
17:44:02.941 T:548278820864  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
17:44:02.959 T:548278820864  NOTICE: Running database version Addons27
17:44:03.006 T:548278820864  NOTICE: ADDONS: Using repository repository.kodi.game
17:44:03.006 T:548278820864  NOTICE: ADDONS: Using repository repository.libreelec.tv
17:44:03.006 T:548278820864  NOTICE: ADDONS: Using repository repository.xbmc.org
17:44:03.006 T:548278820864  NOTICE: ADDONS: Using repository repository.gamestarter
17:44:03.049 T:548278820864   ERROR: AML: no rw on /sys/class/ppmgr/ppmgr_3d_mode
17:44:03.081 T:548278820864  NOTICE: InitWindowSystem: Using EGL Implementation: amlogic
17:44:03.090 T:548278820864  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 60.000000 Hz
17:44:03.090 T:548278820864  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080i @ 60.000000 Hz
17:44:03.090 T:548278820864  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
17:44:03.090 T:548278820864  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 50.000000 Hz
17:44:03.090 T:548278820864  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080i @ 50.000000 Hz
17:44:03.090 T:548278820864  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 50.000000 Hz
17:44:03.090 T:548278820864  NOTICE: Found (1920x1080@60.000000) at 18, setting to RES_DESKTOP at 16
17:44:03.090 T:548278820864  NOTICE: Checking resolution 16
17:44:03.131 T:548278820864  NOTICE: GL_VENDOR = ARM
17:44:03.131 T:548278820864  NOTICE: GL_RENDERER = Mali-450 MP
17:44:03.131 T:548278820864  NOTICE: GL_VERSION = OpenGL ES 2.0
17:44:03.131 T:548278820864  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
17:44:03.131 T:548278820864  NOTICE: GL_EXTENSIONS = GL_OES_texture_npot GL_OES_vertex_array_object GL_OES_compressed_ETC1_RGB8_texture GL_EXT_compressed_ETC1_RGB8_sub_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_mapbuffer
17:44:03.612 T:548262031584  NOTICE: Running database version Addons27
17:44:03.613 T:548262031584  NOTICE: Running database version ViewModes6
17:44:03.614 T:548262031584  NOTICE: Running database version Textures13
17:44:03.621 T:548262031584  NOTICE: Running database version MyMusic60
17:44:03.632 T:548262031584  NOTICE: Running database version MyVideos107
17:44:03.635 T:548262031584  NOTICE: Running database version TV29
17:44:03.637 T:548262031584  NOTICE: Running database version Epg11
17:44:03.639 T:548278820864  NOTICE: start dvd mediatype detection
17:44:03.783 T:547835039968  NOTICE: Register - new cec device registered on cec->AOCEC: CEC Adapter (0000:0000)
17:44:03.793 T:547826651360   ERROR: AddOnLog: Joystick Support: Device "Sony Interactive Entertainment Wireless Controller": can't find <controller> tag
17:44:03.820 T:547826651360  NOTICE: Register - new joystick device registered on addon->peripheral.joystick/0: Twin USB Joystick
17:44:03.843 T:547826651360  NOTICE: Register - new joystick device registered on addon->peripheral.joystick/1: Twin USB Joystick
17:44:03.984 T:548278820864 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
17:44:04.212 T:548278820864  NOTICE: initialize done
17:44:04.213 T:548278820864  NOTICE: Running the application...
17:44:04.232 T:548278820864  NOTICE: starting zeroconf publishing
17:44:04.233 T:548278820864  NOTICE: CWebServer[8080]: Started
17:44:04.233 T:548278820864  NOTICE: starting upnp client
17:44:04.255 T:546861740256  NOTICE: ES: Starting UDP Event server on port 9777
17:44:04.255 T:546861740256  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
17:44:04.495 T:547205673184 WARNING: CSkinInfo: failed to load skin settings
17:44:12.432 T:548278820864  NOTICE: Storing total System Uptime
17:44:12.433 T:548278820864  NOTICE: Saving settings
17:44:12.447 T:548278820864  NOTICE: Saving skin settings
17:44:12.449 T:548278820864  NOTICE: stop all
17:44:12.450 T:548278820864  NOTICE: stop player
17:44:12.450 T:548278820864  NOTICE: ES: Stopping event server
17:44:13.265 T:546861740256  NOTICE: ES: UDP Event server stopped
17:44:13.320 T:548278820864  NOTICE: stopping upnp
17:44:13.473 T:548278820864  NOTICE: stopping zeroconf publishing
17:44:13.502 T:548278820864  NOTICE: CWebServer[8080]: Stopped
17:44:13.502 T:548278820864  NOTICE: stop dvd detect media
17:44:16.544 T:548278820864  NOTICE: clean cached files!
17:44:16.904 T:548278820864  NOTICE: closing down remote control service
17:44:16.906 T:548278820864  NOTICE: stopped
17:44:17.125 T:548278820864  NOTICE: destroy
17:44:17.126 T:548278820864  NOTICE: unload skin
17:44:17.166 T:548278820864  NOTICE: unload sections
17:44:17.178 T:548278820864  NOTICE: special://profile/ is mapped to: special://masterprofile/
17:44:17.185 T:548278820864  NOTICE: application stopped...`

retroarch.log:
`RetroArch [ADDON] :: Wed Oct 24 17:43:53 UTC 2018
============================================================
RetroArch [ADDON] :: RetroPlayer core found: *
RetroArch [ADDON] :: Total RetroPlayer cores: 1
RetroArch [ADDON] :: Kodi is ready.
RetroArch [ADDON] :: WeTek_Play_2.aarch64-8.2.5 - Wed Oct 24 17:43:57 UTC 2018
RetroArch [ADDON] :: Stop kodi...
RetroArch [ADDON] :: Launch Retroarch (Enable debugging and see process output in retroarch_debug.log)
RetroArch [ADDON] :: Restart kodi...`

**Comment by bite-your-idols** [comment]
sorry:  Retrogaming Kodi add-ons for LibreELEC (**RPi2/3 & Generic x86_64**)
