### ISSUE TITLE
AEL Unable to get work

### ISSUE THREAD

**Issue by TheCherry** [bite-your-idols/Gamestarter#106]
I try to use the AEL. (Retroarch just work perfect.)
1. I had a problem to export the AEL-ASSETS from retroarch, there is just no option to do that.
2. I tried to import the assets from your repo (/packages/ael-assets.tar.gz), import it and that worked but ...
3. I had to put it in the directory /storage/emulators/roms/ -> because ael just shows me that directory then I select the import option!
4. Then I tried to import my roms (search ROMs in Launcher) but then he tells me "launcher JSON not found. add Roms to launcher"
  In the log comes only something like that:

```23:11:12.818 T:1945281088  NOTICE: LoadJpeg: unable to load /storage/emulators/roms/ael-assets/Game Boy Advance_icon.jpg
23:11:12.910 T:1945281088  NOTICE: LoadJpeg: unable to load /storage/emulators/roms/ael-assets/NES_icon.jpg
23:11:12.996 T:1945281088  NOTICE: LoadJpeg: unable to load /storage/emulators/roms/ael-assets/Nintendo 64_icon.jpg
23:11:13.083 T:1945281088  NOTICE: LoadJpeg: unable to load /storage/emulators/roms/ael-assets/SNES_icon.jpg        
```
                                                                                                                                                                                          
The strange thing is, that .jpg files are in this place and I can open in regular ...

I looked into the option "view launcher" and there is a ROM directory, that is just correct ...

**Comment by TheCherry** [comment]
Update: OK Its works now better. I did removbe the whole `/storage/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher` directory. But still have to download the assets manual and import them from the rom directory.

**Comment by bite-your-idols** [comment]
To download AEL assets you need to follow steps in documentation. Tip: you need to use Retroarch addon settings in Kodi not in retroach app itself.

**Comment by TheCherry** [comment]
sure in the addon settings and not in RA, but that option is not available!
