### ISSUE TITLE
Rom collection browser - Retroplayer?

### ISSUE THREAD

**Issue by TheCherry** [bite-your-idols/Gamestarter#108]
Is there a way to get the detection for retroplayer from the addon "Rom collection browser" (RCB) done?
Or a way to launch retroarch with this? The autodetect function from RCB don't work and then I set the game.retroarch-RPi binary as emulator, its don't start a rom.

By the way, I prefer RCB, the scraper works and this addon is way much easier to configure.

**Comment by bite-your-idols** [comment]
If you mean retroarch, I guess you can dive into RCB to define what app you want to launch. If yiu don't, you can ask for help in RCB support forum/thread/reddit/github...

**Comment by TheCherry** [comment]
You can define a app for launch, but start directly retrocharch dont work. Did you not modify AEL to use Retroplayer?

**Comment by bite-your-idols** [comment]
Instead of selecting RA binary you should select addon.start file. It is the only thing I can tell you since I never use RCB.
