### ISSUE TITLE
libass.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by psyapathy** [bite-your-idols/Gamestarter#111]
Hello all!

Can you help me please?

My device: Orange Pi Win Plus.
I install LibreELEC for my device from this https://forum.libreelec.tv/thread/13228-very-early-community-images-for-h3-and-a64

I try install Gamestarter 3.0 but Kodi can't install this. Silent.
script.gamestarter-v2.9-LE8.zip successfuly installed.

I try to run 2.9 click OK for close Kodi, i see Gamestarter logo,but then crash and Kodi run again.

I try by shh run ./.kodi/addons/script.gamestarter/resources/bin/retroarch and get error:

`./.kodi/addons/script.gamestarter/resources/bin/retroarch: error while loading shared libraries: libass.so.5: cannot open shared object file: No such file or directory`

In /usr/lib i found libass.so.9

Is that the problem? How can it be corrected? Thanks in advance

**Comment by bite-your-idols** [comment]
you can try getting that lib and any other missing lib but I think it will not work since this project is just for Raspberry Pi 2/3 and Generic x86_64 PCs...
