### ISSUE TITLE
Incompatible to raspbian kodi

### ISSUE THREAD

**Issue by vendetta1987** [bite-your-idols/Gamestarter#113]
Although this came up before I'd like to bring up the usage of this addon with the raspbian version of kodi 18.x again. I have it installed on a headless raspbian running on an RPi3 and set to autostart and output over HDMI. I started out after adding your repo and the retroarch addon.
While fiddling around I managed to make the latest version start/stop kodi and more or less start the game.retroarch-RPi executable. The latter doesn't yet do anything useful but it's a start. Maybe you can iterate from here on?
The given script is provided with no warranty as it is written down from the top of my head after trying for hours. Be careful about the visudo part especially.

```shell
#!/bin/bash

#add missing LibeELEC directory and link to actual kodi user folder
sudo mkdir /storage
sudo chown pi:pi /storage
cd /storage
ln -s /home/pi/.kodi .kodi

#add release file
#copied from current LibeELEC release .img -> /etc/release
echo RPi2.arm-9.0.1 > release
sudo ln -s release /etc/release

#allow user to control kodi and run the addon scripts with sudo
echo "Cmnd_Alias CONTROL_KODI = /usr/bin/systemctl start kodi, /usr/bin/systemctl stop kodi, /storage/.kodi/addons/game.retroarch/" | sudo EDITOR="tee -a" visudo -f /etc/sudoers.d/010_kodi_gamestarter
echo "pi ALL=(ALL) NOPASSWD: CONTROL_KODI" | sudo EDITOR="tee -a" visudo -f /etc/sudoers.d/010_kodi_gamestarter

#add missing libs as reported by game.retroarch-RPi
sudo apt install speex
sudo echo "/home/pi/.kodi/addons/game.retroarch/lib" > /etc/ld.so.conf.d/kodi_gamestarter_libs.conf
sudo ln -s /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.2 /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
sudo ln -s /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.2 /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0
sudo ldconfig

#add seemingly missing assets to libretro config folder
cp -r ~/.kodi/userdata/addon_data/game.retroarch/assets/* ~/.config/retroarch/assets
```

**Comment by bite-your-idols** [comment]
I don't know how to make it work in non LibreELEC systems but if you want RetroArch work in raspbian, you can grab it binary from retropie... or even easier, use retropie that includes kodi and you can set which distro to run at boot.
