### ISSUE TITLE
[Request] Add libretro Ludo front-end

### ISSUE THREAD

**Issue by jonian** [bite-your-idols/Gamestarter#114]
Hi, thank you for your great work. There is a new minimal libretro front-end that would be nice to add.

Ludo Repo: https://github.com/libretro/ludo
LudOS Repo: https://github.com/libretro/LudOS

**Comment by bite-your-idols** [comment]
It is an interesting project, I tried it out some weeks ago, but it is at very early development stage, so maybe in the future ...
