### ISSUE TITLE
Crash on startup on Libreelec Milhouse Leia

### ISSUE THREAD

**Issue by seanrand** [bite-your-idols/Gamestarter#116]
Retroarch crashes on startup on Milhouse Libreelec Leia Generic builds since build #303 because openssl got updated.

```
game.retroarch-Gen: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

game.retroarch-Gen: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by bite-your-idols** [comment]
does it work using official LE 9? by the way what is the point of using testbuilds of an official kodi version? what is your device?

**Comment by bite-your-idols** [comment]
If you could zip and upload them over here I can include them in the next addon release.

**Comment by ezar** [comment]
Please!!!

**Comment by bite-your-idols** [comment]
@ezar, device? LibreELEC version?

**Comment by ezar** [comment]
Rpi 3, LibreELEC Milhouse 9.1 build.

**Comment by bite-your-idols** [comment]
I cross-compile RetroArch using Lakka, that is using LE8, So untill Lakka project get updated to LE9 I am afraid I can not do anyyhing about it. 
Only thing that can be done is manually grab missing libs from another distro like @seanrand did.

**Comment by ezar** [comment]
@bite-your-idols, thanks
@seanrand, please can you send missing files?

**Comment by ezar** [comment]
Copied @ lib folder inside game.retroarch addon.

[libs-LE91.zip](https://github.com/bite-your-idols/Gamestarter/files/3129053/libs-LE91.zip)

**Comment by ezar** [comment]
Can you add this libs to last version please?

**Comment by bite-your-idols** [comment]
I preffer to let addon clean and working with latest official LE release. Since Milhouse builds are for testing purposes this is not he common scenario, so anyone using those builds can come here and download the additional libs zip zile.  Also, I can't be sure that including those libs will not affect to official LE9 and LE8 users...

**Comment by bite-your-idols** [comment]
it should work with latest update, in beta version yet: https://github.com/bite-your-idols/Gamestarter/raw/master/repository.gamestarter/game.retroarch/game.retroarch-9.178.15.zip

feedback is welcome

**Comment by haeihaiehaei** [comment]
I´m getting crashes using RetroArch as well on my Rpi4b running ELEC 9.1, even tried the beta you listed here, is there anything I can do to help getting this solved?

**Comment by haeihaiehaei** [comment]
Alright, thanks a lot for your answer, I´ll keep my eyes open then :)

**Comment by ezar** [comment]
I confirm that works using Milhouse betas. LE 9.8
Regards,
