### ISSUE TITLE
Help setting this up on Fedora

### ISSUE THREAD

**Issue by kommulu** [bite-your-idols/Gamestarter#117]
Hi,
I am trying to setup Gamestarter and the related addons on Fedora 29 on a Intel NUC.

I mimicked the directory-layout of llibreelec and symlinked some libraries you include in emulatiostation to resolve some initial errors, but now I kind of hit a hard one:
When trying to start emulationstation if fails and the debug_log shows me this error:

`/storage/.kodi/addons/game.emulationstation/game.emulationstation-Gen: /lib64/libcurl.so.4: no version information available (required by /storage/.kodi/addons/game.emulationstation/game.emulationstation-Gen)
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid`

I suspect you run some kind of check here inside the binary?
Fedora/standard Linux might not be the scope of this project, but can you maybe help me?

**Comment by bite-your-idols** [comment]
Gamestarter addons binaries are compiled for LibreELEC so they will not work in fedora... You need to compile them by yourself to work in that OS

**Comment by kommulu** [comment]
Hm..okay.
So, how and what did you compile there?
