### ISSUE TITLE
Can you build latest retroarch git?

### ISSUE THREAD

**Issue by ezar** [bite-your-idols/Gamestarter#119]
Hi, I want to resolve this: https://github.com/libretro/RetroArch/issues/8683
Can you build or explain how I can build?
Regards,

**Comment by bite-your-idols** [comment]
I will compile again when new RA version releases or when lakka update to LE 9. In the meantime, you can compile by yourself:
http://www.lakka.tv/doc/Compiling-Lakka/

**Comment by ezar** [comment]
Gracias!

**Comment by ezar** [comment]
Can you update to Retroarch 1.7.7 :)

**Comment by bite-your-idols** [comment]
I tried but it fails due to opengl... So I will take a look when I get some free time or lakka updates... Sorry...

**Comment by ezar** [comment]
Ok :)

**Comment by bite-your-idols** [comment]
https://github.com/bite-your-idols/Gamestarter/releases/tag/RA-8.177.14
