### ISSUE TITLE
Black screen when launching Retroarch or EmulationStation

### ISSUE THREAD

**Issue by neilsimp1** [bite-your-idols/Gamestarter#120]
I have Kodi running on Arch 32 on and old Dell Latitude 810. I was hoping to get some more life ot of it by seeing if could run Kodi and emulators.
I have Kodi working fine on it now but I've tried starting both Retroarch and EmulationStation through Gamestarter with no luck. Both show only a black screen and exit when I press Esc.

Other issues point to a log file at `/storage/.kodi/userdata/addon_data/script.gamestarter/gamestarter.log`. Since this is run for me out of `/var/lib/kodi/` I have looked in `/var/lib/kodi/.kodi/userdata/addon_data/` but do not see anything besides game.retroarch and game.emulationstation folders, neither of which contain any logs.

I am using Kodi through [kodi-standalone-service](https://github.com/graysky2/kodi-standalone-service), but the same thing happens if I boot into XFCE, run Kodi, and then try the Gamestarter.
I also have installed Retroarch outside of Gamestarter and am able to launch it from within XFCE.

Are there any other log locations I should be looking for? Here is [/var/lib/kodi/.kodi/temp/kodi.log](https://pastebin.com/Lei5wVG4). It mentions `ERROR: Error loading the current image 0: /storage/.kodi/addons/game.retroarch/fanart.jpg`.
I found a config.uae file that points to `/storage/...` often, but is there one global place I can repoint everything to `/var/lib/kodi/.kodi/addons/`?

Arch Linux 32 i686 5.0.7-arch1-1.0-ARCH
Kodi 17.6

**Comment by bite-your-idols** [comment]
These addons are for kodi running under LibreELEC... I guess you need to find another source to get retroarch and/or emulationstation for your distro.

**Comment by neilsimp1** [comment]
Hm. Ok, I saw it was for LibreELEC but was hoping it would still work on other distros. I would use LibreELEC too if there was a 32bit version of it.
If I could find some Kodi addon to just launch any arbitrary program that you configure, that would be perfect.
