### ISSUE TITLE
libass.so.5 not found

### ISSUE THREAD

**Issue by kommulu** [bite-your-idols/Gamestarter#121]
Hi,
I've set up RetroArch and EmulationStation on LE 9.0.2 (running on a Intel Nuc)
It starts just fine, but whenever I try to start a game, the screen just goes black for a few seconds and I land back in the ES interface.
The log says:

`/storage/.kodi/addons/game.retroarch/game.retroarch-Gen: error while loading shared libraries: libass.so.5: cannot open shared object file: No such file or directory`

But I can find this lib in the lib-dir of the addon.
Any clue how to fix this?
Tried it with reinstalling, did not work.

**Comment by bite-your-idols** [comment]
I just updated my RPI2 to LE 9.0.2 and it still works ok. 
Did you try launching retroarch without EmulationStation and without any ROM?
Did you reboot your device after installing RA addon?

**Comment by kommulu** [comment]
Hi,
I rebooted multiple times, but that did not fix anything sadly.

**Comment by bite-your-idols** [comment]
Yesterday I updated Retroarch addon and I tried in my laptop running LE GEn 9.0.2 and it worked ok...
Did you try launching just retroarch addon, without EmulationStation and without any ROM?

**Comment by kommulu** [comment]
Hi,
I tried it now with plain retroarch and the game actually started, but without sound.
I only found this error in the logs:

`[INFO] [MIDI]: Initializing ...
ALSA lib /var/lib/jenkins/LE/build2/workspace/Generic/build.LibreELEC-Generic.x86_64-9.0.2/alsa-lib-1.1.8/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
[ERROR] [MIDI]: snd_seq_open failed with error -2.
[ERROR] [MIDI]: Initialization failed (list of input devices unavailable).`

**Comment by bite-your-idols** [comment]
so retroarch works. Audio issue seems like is something related to your libreelec audio config or maybe retroarch audio settings... you can take a look to other closed issues, I remember some of them related to audio

**Comment by kommulu** [comment]
I will check on that sound issue next, yes.
Any clue why games work with retroarch, but not with emulationstation? It is a lot easier to use for people who are less tech-savy.

**Comment by bite-your-idols** [comment]
The easiest way to launch emulators is using AdvanceEmulatorLauncher, if you want to use EMulationStation you could consider using lakka, retropie or recalbox. Anyways, if retroarch is working, launching it from emulationstation should work too, maybe any addon you have installed creates a conflict with lib folder inside retroarch addon but I really don't know... i'm sorry...

**Comment by kommulu** [comment]
Okay, thanks a lot. I think this gave me enough leads.
