### ISSUE TITLE
Add retroelec support for xu4

### ISSUE THREAD

**Issue by camatthew** [bite-your-idols/Gamestarter#122]
I was wanting to use retroelec on my xu4 with iagl but I think gamestarter would be easy to setup. Can you enable retroelec support for xu4 with this addon.

**Comment by bite-your-idols** [comment]
There is no point to integrate gamestarter addons in retroeelec, since both of them use retroarch and emulationstation.
I am not going to add support for a device I do not own and a device is not officially supported by LIbreELEC... sorry
