### ISSUE TITLE
Lakka Updates libretro package

### ISSUE THREAD

**Issue by ezar** [bite-your-idols/Gamestarter#123]
Hi,
Can you update cores?

https://github.com/libretro/Lakka-LibreELEC/commit/7e2eaa4a437b03d9414f23fbe9e9e108e7f224a6

**Comment by bite-your-idols** [comment]
it seems @kivutar is preparing a new Lakka update. I will update core package when lakka updates.
In the meanwhile you can try to download cores from libretro buildbot using retroarch core downloader option.

**Comment by ezar** [comment]
ok
