### ISSUE TITLE
retroarch controller autoconfig files need updating

### ISSUE THREAD

**Issue by yoyoma2** [bite-your-idols/Gamestarter#125]
The retroarch autoconfig files installed by this libreelec add-on are outdated and include a broken Logitech_RumblePad_2_USB.cfg

Gamestarter/repository.gamestarter/game.retroarch/retroarch/autoconfig/udev/

It is impossible to navigate retroarch since no keyboard/mouse are connected.  Workaround by logging in by ssh and manually replacing gamestarter's Logitech_RumblePad_2_USB.cfg with the current one from libretro/retroarch-joypad-autoconfig/udev/

The next time gamestarter updates, the obsolete/broken autoconfig files overwrite the current/fixed one and retroarch is broken again.

**Comment by drrak** [comment]
_Translator:_
Can you write more precisely where to get the correct cfg file?

**Comment by bite-your-idols** [comment]
updated!
