### ISSUE TITLE
Retroarch and Kodi Leia 18.3 with Pi4 4GB

### ISSUE THREAD

**Issue by CloudStrife772** [bite-your-idols/Gamestarter#126]
I just got a Rasperry Pi 4 4GB and tried to install Retroarch from your repository like on my old Pi3. Unfortunately Kodi just restarts when opening Retroarch and won't start. 
It works with Retroarch 9.80 like here: https://forum.libreelec.tv/thread/17830-libreelec-retroarch-9-80-for-raspberry-pi-4/?pageNo=1
But there where playback-issues with this build. Is there a solution for this or are you working on it?

**Comment by bite-your-idols** [comment]
There is no RPi4 support yet, it is on my roadmap, but no ETA.
