### ISSUE TITLE
Unable to open any plugins, kodi always restarts

### ISSUE THREAD

**Issue by kero990** [bite-your-idols/Gamestarter#127]
Whether I run retroarch, ppsspp, or emulationstation, The kodi will restart
The logs for the three plugins are as follows:

```
EmulationStation [ADDON] :: Wed Jul 31 10:00:59 UTC 2019

EmulationStation [ADDON] :: Kodi is ready.
EmulationStation [ADDON] :: AMLGX.arm-devel-20190725113906-893dd58 - Wed Jul 31 10:01:03 UTC 2019
EmulationStation [ADDON] :: Stop kodi...
EmulationStation [ADDON] :: Launch EmulationStation (See process output in emulationstation_debug.log)
EmulationStation [ADDON] :: Restart kodi...
```

The debug file error is similar to the missing file.
**emulationstation:**
`/storage/.kodi/addons/game.retroarch/addon.start: line 93: /storage/.kodi/addons/game.emulationstation/game.emulationstation-AML: not found
`
**ppsspp:**
`/storage/.kodi/addons/game.ppsspp/game.ppsspp: error while loading shared libraries: libbcm_host.so: cannot open shared object file: No such file or directory
`

**retroarch:**
`/storage/.kodi/addons/game.retroarch/addon.start: line 87: /storage/.kodi/addons/game.retroarch/game.retroarch-AML: not found
`

How can I solve these problems? What is missing from the error with the -AML suffix?
I just found libreelec that fits my device, I am not sure if the system is not perfect.
Please help me see, thank you

PS: The above is from Google Translate, I hope you can understand.

**Comment by kero990** [comment]
另外，我的libreelec是aarch64架构编译的，请问这跟我的错误有关系吗？

**Comment by bite-your-idols** [comment]
Sorry, but these addons are just for generic and rpi 2/3 devices.
