### ISSUE TITLE
Retroarch controller

### ISSUE THREAD

**Issue by mvnitro** [bite-your-idols/Gamestarter#129]
I have a mocute 050 control and a bluetooth adapter, they work perfectly on windows + retroarch and libreelec (PC)

However, when I enter the retroarch the control is detected but does not work, his name appears in the configuration but when I try to bind the button he always gets the same button is like '' -4 (n / d) '' this is the right kitten , I thought it was a problem in the control I got my other mocute and the same thing happened, a detail is that when I do this bind the keyboard of my other multmedia control stops working and only the mouse function is working

I saw that some autoconfig files have been updated, I tried to reinstall retroarch by gamestarter but it is not working yet!

**Comment by bite-your-idols** [comment]
You need to update manually using this zip:
https://github.com/bite-your-idols/Gamestarter/raw/master/repository.gamestarter/game.retroarch/game.retroarch-9.178.15.zip
 or you can update just autoconfig folder using libretro's one: 
https://buildbot.libretro.com/assets/frontend/autoconfig.zip

**Comment by mvnitro** [comment]
unzipped the file in the folder but did not resolve
Is the location correct?

/storage/.kodi/userdata/addon_data/game.retroarch/autoconfig

on emulationstation is also working perfectly

**Comment by bite-your-idols** [comment]
Yes, that is the default location, if you want, you can asign another one in retroarch settings.
If the problem with your controller still not working, I recomend you to go to retroarch forums, maybe other users can help you, sorry.
