### ISSUE TITLE
How I test beta version?

### ISSUE THREAD

**Issue by ezar** [bite-your-idols/Gamestarter#130]
I want to test RA:9.178.15 beta 2 but I cannot to update?

**Comment by bite-your-idols** [comment]
you have to download zip and paste it into your pi, then install it:
https://github.com/bite-your-idols/Gamestarter/raw/master/repository.gamestarter/game.retroarch/game.retroarch-9.178.15.zip
As soon as I get report that is working OK both in RPI and Generic devices running LE9.2 I will include it in the gamestarter repo to notify users about the update.
