### ISSUE TITLE
Retroarch crashes on Libreelec latest (9.1.501). RPi4 

### ISSUE THREAD

**Issue by wonder75** [bite-your-idols/Gamestarter#131]
After starting RetroArch from the repo, the startup screen is displayed. (The one with the box full of consoles and the RetroArch logo).

After a few seconds  RetroArch crashes and the system restarts Kodi.

# Retroarch Debug Log
[INFO] RetroArch 1.7.8 (Git ea7e682)
[INFO] === Build =======================================
[INFO] Capabilities: NEON VFPv3 VFPv4 
[INFO] Built: Sep 20 2019
[INFO] Version: 1.7.8
[INFO] Git: ea7e682
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/storage/emulators/saves/.srm".
[INFO] Redirecting savestate to "/storage/emulators/saves/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ 960x720
* failed to add service - already in use?

**Comment by bite-your-idols** [comment]
Sorry no RPi4 support yet, just RPi2/3 and Generic.
