### ISSUE TITLE
Very slow pcsx rearmed on RetroArch (9.178.15) and RPi3

### ISSUE THREAD

**Issue by drrak** [bite-your-idols/Gamestarter#132]
_Translator:_
Do you also have such problems with PS1 emulation? Everything worked fine on the old version of LE and RA.

_LibreELEC 9.1.501, RetroArch 9.178.15, RPi3_

**Comment by bite-your-idols** [comment]
try going back to previous RA version, if it still works better it is something related to retroarch, if it doesn't, it can be related with latest lakka cores...

**Comment by drrak** [comment]
8.177.14 and 8.176.13 on LE 9.1.501 does not work. After RA wallpaper is back to Kodi.

**Comment by drrak** [comment]
I replaced the pcsx rearmed cores and it works as before.
Here you can download a working core:
https://drive.google.com/file/d/10R8ARwEmxLqfkc7LN_AK57IVoK0GmZHX/view?usp=sharing

**Comment by bite-your-idols** [comment]
you're right... 8.xxx.xx addons don't work in LE9.2... you need to perform taht test in LE8, but maybe there latest addon version doesn't work...

anyways, what rearmed core are you using? the one from latest lakka 2.3 package download, one from libretro buildbot, or from retroplayer?

you can try the one from previous lakka 2.2 from here: https://github.com/bite-your-idols/Gamestarter/raw/RA-8.177.14/packages/libretro-cores-RPi/pcsx_rearmed_libretro.so

**Comment by drrak** [comment]
From libretro. Old file works. Thanks.

**Comment by bite-your-idols** [comment]
ok, so the bad one is coming with lakka 2.3, good to know that, thank you.
