### ISSUE TITLE
Won't run on rpi4.

### ISSUE THREAD

**Issue by htremmel** [bite-your-idols/Gamestarter#134]
Thank you very much for your work.  Below is the issue I'm having.

_emulationstation_debug.log_
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted
```

Using https://goo.gl/m36qLT

**Comment by bite-your-idols** [comment]
Sorry no RPi4 support yet, just RPi2/3 and Generic.

https://github.com/bite-your-idols/Gamestarter/issues/131
https://github.com/bite-your-idols/Gamestarter/issues/126
