### ISSUE TITLE
Raspberry Pi 4

### ISSUE THREAD

**Issue by bite-your-idols** [bite-your-idols/Gamestarter#135]
I am trying to make retroarch work in RPi4... here is the latest addon beta:

https://github.com/bite-your-idols/Gamestarter/raw/master/repository.gamestarter/game.retroarch/game.retroarch-9.178.15-4.zip

This addon beta must work in Rpi 2, 3 and 4 (also Generic devices) running LibreELEC 9.2 beta but I didn't test it by myself yet...

Testing is needed ( or ... RPi4 needed XD ) !!!

feedback is welcome!

**Comment by Seilmeister** [comment]
Hi bite,
Thanks for your amazing work =)
I will test it today (if possible) and let you know the results.

**Comment by khimaros** [comment]
RetroPie launches and basic interface works with LibreELEC Leia on an RPi4 with the provided zip. Previously, it was crashing on launch. I was also able to update assets with the online updater. I have not yet tested any ROMs.

**Comment by GuilleDF** [comment]
I can confirm it launches on my RPi4 with LibreELEC 9.1.501 (kodi 18.4). I've also tested super mario world with the snes9x core and it runs, albeit very slowly (but that might be fixed by tuning the RetroArch config). If there's anything specific you'd like to test on a RPi4, just ask, I can be your beta tester :smiley:

**Comment by k0st1x** [comment]
@bite-your-idols thank you for your good job!
the retroarch starts normally but with some nuances.

the emulation station (from repository, not some beta) closes unexpectedly with 
> emulationstation_debug.log
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted
```
is this libreelec's issue or emulationstation's?

**Comment by bite-your-idols** [comment]
@k0st1x some LibreELEC forum users say the following:

> I can confirm that after installing the locale addon and changing it to en_US.UTF-8 on the addon's settings, emulationstation now runs normally.

As you can read aver here: https://forum.libreelec.tv/thread/287-gamestarter-retrogaming-add-ons-rpi-generic/?postID=129049#post129049

take a look and post your feedback

**Comment by k0st1x** [comment]
@bite-your-idols oki

**Comment by ezar** [comment]
Error using this beta4

2019-11-10 21:05:57.420 T:2991   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'TabError'>
                                            Error Contents: inconsistent use of tabs and spaces in indentation (addon.py, line 100)
                                              File "/storage/.kodi/addons/game.retroarch/addon.py", line 100
                                                os.system("PROJECTPI=$(head -c 4 /etc/release) && if [[ $PROJECTPI == 'RPi4' ]] ; then mv -n /storage/.kodi/addons/game.retroarch/game.retroarch-RPi /storage/.kodi/addons/game.retroarch/game.retroarch-RPi2 && mv -n /storage/.kodi/addons/game.retroarch/game.retroarch-RPi4 /storage/.kodi/addons/game.retroarch/game.retroarch-RPi ; fi")
                                                                                                                                                                                                                                                                                                                                                                                             ^
                                            TabError: inconsistent use of tabs and spaces in indentation
                                            -->End of Python script error report<--

**Comment by bite-your-idols** [comment]
@ezar device and LE version?

**Comment by ezar** [comment]
Raspberry 3b+ and LE9.8
Using beta3 works fine :)

**Comment by bite-your-idols** [comment]
LE 9.8? so, are you running mildhouse testbuilds?

**Comment by ezar** [comment]
Yes!

**Comment by bite-your-idols** [comment]
Sorry, no 9.8 testbuild support yet, first we need official 9.2 release.

**Comment by MikailCZ** [comment]
Is there any way to run this in Kodi on Raspbian? I've tried it but I only get black screen when launching RetroArch.

**Comment by bite-your-idols** [comment]
Just for LibreELEC.

**Comment by straytachyon** [comment]
https://github.com/bite-your-idols/Gamestarter/raw/master/repository.gamestarter/game.retroarch/game.retroarch-9.178.15-4.zip
is no longer available.  Can you please provide the latest compilation?

Thanks a lot

**Comment by bite-your-idols** [comment]
you just need to install latest retroarch release, it is working ok in RPi4.

By the way, since RA is working in RPi4 i am going to close this issue.

**Comment by ezar** [comment]
> Sorry, no 9.8 testbuild support yet, first we need official 9.2 release.

> try:
>     import urlparse
> except ImportError:
>     import urllib.parse as urlparse

And fix some identations. Before that works  using LE9.8 :)

**Comment by bite-your-idols** [comment]
please, open a new issue regarding LE9.8 testbuilds

**Comment by pablinho1023** [comment]
Hi!

@bite-your-idols I really want to cangratulate and thank for your awesome work!
I used gamestarter for some years in a rpi 3 with openelec. However, I updated to Openelec 8.0 and now it retroarch and emulation station doesn't boot. Could you help me?

Thank you so much!

**Comment by bite-your-idols** [comment]
Just switch to LibreELEC 9.
