### ISSUE TITLE
RetroArch does not start under LibreELEC

### ISSUE THREAD

**Issue by update-freak** [bite-your-idols/Gamestarter#136]
I rebuilt LibreELEC (9.1.501) on my RPi3 model B and then installed RetroArch (8.177.14) from the Gamestarter repository. If I want to start RetroArch, comes the message that Kodi will leave, however, the surface of Kodi appears again.

**Comment by bite-your-idols** [comment]
You must use addon beta version:
https://github.com/bite-your-idols/Gamestarter/raw/master/repository.gamestarter/game.retroarch/game.retroarch-9.178.15-4.zip

https://github.com/bite-your-idols/Gamestarter/issues/116

**Comment by update-freak** [comment]
ok, thanks!
