### ISSUE TITLE
EmulationStation on Kodi v18.4 "Leia"

### ISSUE THREAD

**Issue by k0st1x** [bite-your-idols/Gamestarter#137]
the emulation station closes unexpectedly with

> emulationstation_debug.log

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted
```

~~workaround: https://forum.libreelec.tv/thread/287-gamestarter-retrogaming-add-ons-rpi-generic/?postID=129049#post129049~~

**Comment by bite-your-idols** [comment]
Please, comment your device and LE version, and if this workaround worked for you.

`I can confirm that after installing the locale addon and changing it to en_US.UTF-8 on the addon's settings, emulationstation now runs normally.`

**Comment by k0st1x** [comment]
> Please, comment your device and LE version, and if this workaround worked for you.
LE 9.1.501
workaround doesn't work :(

**Comment by bite-your-idols** [comment]
did you try what also is commented in that thread?
https://forum.libreelec.tv/thread/287-gamestarter-retrogaming-add-ons-rpi-generic/?postID=129132#post129132
https://forum.libreelec.tv/thread/287-gamestarter-retrogaming-add-ons-rpi-generic/?postID=129134#post129134

**Comment by k0st1x** [comment]
@bite-your-idols yes, i've tried to install locale tool addon set it to "en_US.UTF-8" and reset the device, but it wont fix issue. also i've tried to run python script in ssh terminal
> python
>>Python 2.7.16 (default, Sep  2 2019, 20:11:29)
>>[GCC 8.3.0] on linux2
>>Type "help", "copyright", "credits" or "license" for more information.

>import locale
locale.getlocale()
>>(None, None)

im not the linux-python-guy, but is this command can say that the locale is not set?

**Comment by bite-your-idols** [comment]
I really don't know... but happy to hear it worked again for you!
