### ISSUE TITLE
Game addons - emulators - there is no mupen64

### ISSUE THREAD

**Issue by k0st1x** [bite-your-idols/Gamestarter#138]
can't find mupen64 nether in libreelec repository nor in RetroArch cores ("download cores" menu item).
is it possible to run n64 roms?
where can I address this issue?

**Comment by bite-your-idols** [comment]
You can go to RetroArch addon settings and download lakka core package, then you will get mupen64 as you can see here: 
RPi2/3: https://github.com/bite-your-idols/Gamestarter/tree/master/packages/libretro-cores-RPi
RPi4: https://github.com/bite-your-idols/Gamestarter/tree/master/packages/libretro-cores-RPi4
Gen: https://github.com/bite-your-idols/Gamestarter/tree/master/packages/libretro-cores-Gen

**Comment by k0st1x** [comment]
@bite-your-idols  wow!
why i can't find all this stuff on official addons repository?
and what the difference between RPi(s) repo and Gen repo?

**Comment by bite-your-idols** [comment]
Generic PC: https://libreelec.tv/downloads/generic-x86/

**Comment by k0st1x** [comment]
how can i influence mupen64 addon to appear in the official kodi repository?

**Comment by bite-your-idols** [comment]
https://forum.kodi.tv/forumdisplay.php?fid=292

**Comment by k0st1x** [comment]
@bite-your-idols i mean, the other libretro gaming addons like mgba gpsp and other, are maintained by you or somebody?

**Comment by bite-your-idols** [comment]
AFAIK there are no libretro addons, just retroarch addon or libretro cores to use with retroplayer, the kodi gaming project (the link I posted before). If you are talking about that, you should go to kodi forum using provided link and ask devs for missing cores. Official libretro/retroarch team cores for linux are over here: https://buildbot.libretro.com/nightly/linux/x86_64/latest/ 
The ones that can be downloaded within retroach addon settings, the ones in my repo,  are the ones coming with Lakka, the official retroarch distro.

**Comment by k0st1x** [comment]
@bite-your-idols thanks for detailed description and patience.
