### ISSUE TITLE
LE9.8 testbuilds

### ISSUE THREAD

**Issue by ezar** [bite-your-idols/Gamestarter#141]
Actual python script doesn't works using LE9.8 because system uses python 3.x
Regards.

**Comment by bite-your-idols** [comment]
Error using this beta4

2019-11-10 21:05:57.420 T:2991   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'TabError'>
                                            Error Contents: inconsistent use of tabs and spaces in indentation (addon.py, line 100)
                                              File "/storage/.kodi/addons/game.retroarch/addon.py", line 100
                                                os.system("PROJECTPI=$(head -c 4 /etc/release) && if [[ $PROJECTPI == 'RPi4' ]] ; then mv -n /storage/.kodi/addons/game.retroarch/game.retroarch-RPi /storage/.kodi/addons/game.retroarch/game.retroarch-RPi2 && mv -n /storage/.kodi/addons/game.retroarch/game.retroarch-RPi4 /storage/.kodi/addons/game.retroarch/game.retroarch-RPi ; fi")
                                                                                                                                                                                                                                                                                                                                                                                             ^
                                            TabError: inconsistent use of tabs and spaces in indentation
                                            -->End of Python script error report<--

_Originally posted by @ezar in https://github.com/bite-your-idols/Gamestarter/issues/135#issuecomment-552229784_

**Comment by bite-your-idols** [comment]
I need to get some free time to take a look to this

**Comment by bite-your-idols** [comment]
It says problem is in tab indentation at [line 100 ](https://github.com/bite-your-idols/Gamestarter/blob/master/repository.gamestarter/game.retroarch/addon.py#L100)

can you please try editing addon.py file and removing both lines 99 and 100.
if you use RPi4 you have to rename manually "game.retroarch-RPi4" to "game.retroarch-RPi"

**Comment by ezar** [comment]
Here is the corrected file -->
[addon.py.zip](https://github.com/bite-your-idols/Gamestarter/files/3935107/addon.py.zip)

**Comment by bite-your-idols** [comment]
thanks! is this file working ok both in LE testbuilds and LE 9.2 official?

**Comment by ezar** [comment]
yes

**Comment by bite-your-idols** [comment]
thanks a lot for your collaboration!
https://github.com/bite-your-idols/Gamestarter/commit/41703b11ea982c0ceaf36611aa03b6c45f326eaf
