### ISSUE TITLE
Question about RA versions

### ISSUE THREAD

**Issue by johnlabor** [bite-your-idols/Gamestarter#142]
Hi,
Thanks for the repo.
I found that RA is 1.7.x. Compare to the currently release of 1.8.1, seems like a bit old at this point.
Is there a reason that RA is keeping this old version? Thanks.

**Comment by johnlabor** [comment]
Also, this version only has gl video driver, and cannot run .glsl shaders compares to the one on emulation station. I can only run .glslg shader which is very resource consuming.

**Comment by bite-your-idols** [comment]
It is just a matter of free time... I'm sorry... 
Which one is "the one on emulationstation"? emulationstation is just a front end...

**Comment by johnlabor** [comment]
Sorry, I was meant to say the RA used on retropie is able to run .glsl shaders, while the gamestarter seems only accept .glslg shaders, which requires high performance hardware so a pi could not handle it well.

Thanks for your effort, I am already very satisfied with it, so that I dont need to do a berryboot just to install retroarch alongside the libreelec system.

**Comment by bite-your-idols** [comment]
ok, you can try it by yoursefl over here, before I push the update to repo: https://github.com/bite-your-idols/Gamestarter/raw/master/repository.gamestarter/game.retroarch/game.retroarch-9.181.16.zip

enjoy!

**Comment by johnlabor** [comment]
Thanks Very Much! I will for sure try it out!
