### ISSUE TITLE
how about update emulationstation?

### ISSUE THREAD

**Issue by skoworodker** [bite-your-idols/Gamestarter#143]
Hello.
ES version in repo above 3year. In current version fixed/rebuild game scraper for changed API.

**Comment by bite-your-idols** [comment]
I am afraid it will never get updated, I tried several times but I can not compile by myself, the one in the repo was grabbed from another compilation and both LE and that compilation have evolve in different ways so I tried to grab it again and everything fails... 
I recommend to Use retroarch UI or Advanced emulator launcher, or also you can use retroplayer itself... If you want to use emulationstation you better move to RetroPie or Another community LE build.
