### ISSUE TITLE
"Download AEL Assets" option missing from release pacakges

### ISSUE THREAD

**Issue by amura11** [bite-your-idols/Gamestarter#144]
I recently installed the RA 9.181.16 addon and noticed there was no option to download AEL Assets. Looking at the source in the option is there but looking at the addon settings on my machine it's not there. Looking at the 'game.retroarch-9.181.16.zip' and 'game.retroarch-9.178.15.zip' both are missing the option in 'settings.xml'.

I've seen a few comments in closed issues saying they can't find the option to download AEL Assets, this is likely why.

**Comment by bite-your-idols** [comment]
it should be fixed in RA-9.182.17
