### ISSUE TITLE
Mame 2003 plus not running games correctly

### ISSUE THREAD

**Issue by AlexPaterson77** [bite-your-idols/Gamestarter#145]
Hi ! First of all, thank you for your great work !
I have been using the gamestarter verson of retroarch since 2017 and I remember having no problem with the previous core versions. 
Now, after a fresh install of libreelec 9.2 and a fresh install of retroarch, I am experiencing an issue running mame 0.78 roms with the mame 2003 plus addon (I installed the full core package via kodi settings).

It actually runs almost every rom I try, though it slows down (when it does not completely stop working) every 15-20 seconds. I suppose the issue is its experimental nature.

I tried downloading the mame 2003 core from retroarch, but it often breaks the retroarch interface, and goes back to kodi.

I wonder how to get back at playing mame as I did 12 months ago :)

Thank you !

**Comment by bite-your-idols** [comment]
yes, I noticed that in my RPi4 also... it is something in the develooment of that core... I upated my romset from 0.78 to 0.139 so I can play that roms in Mame2010 that works very smooth. Maybe in next Lakka update they will improve that core.

In the meantime, if you don't want to switch to 0.139 romset, you can go to [releases page](https://github.com/bite-your-idols/Gamestarter/releases) scroll down to an older version and download source code zip, then pass the cores to your Pi manually.
