### ISSUE TITLE
(Hyperion) Ambilight on the RPi3 didn't work

### ISSUE THREAD

**Issue by update-freak** [bite-your-idols/Gamestarter#146]
With the latest RetroArch 9.184.18 on the RPi3 (LibreELEC) the Hyperion Ambilight no longer works (in an earlier version it was still possible and in LibreELEC it also works)

**Comment by bite-your-idols** [comment]
It still works ok in my RPi4.... please, check if you have all your hyperion settings ok...

**Comment by update-freak** [comment]
just reinstalled LibreELEC.
Now it works without problems with Ambilight.
Thank you for your prompt reply.
