### ISSUE TITLE
Update PPSSPP assets to fix PS4 Controller

### ISSUE THREAD

**Issue by jonian** [bite-your-idols/Gamestarter#147]
Hi, the PS4 controller is not working with the assets provided. After updating `gamecontrollerdb.txt` from https://github.com/hrydgard/ppsspp, it works.

**Comment by bite-your-idols** [comment]
Are you talking about libretro psp core or experimental standalone addon?

**Comment by jonian** [comment]
Sorry, I wasn't specific. I'm referring to PPSSPP standalone addon.

**Comment by bite-your-idols** [comment]
I'm sorry, that addon was just an experiment I made some years ago and is no longer maintained, so there is no plan to update it... If you get your DS4 working with that file I'm happy and I hope if someone else is getting that issue can solve it wth your help. Sorry again.

**Comment by jonian** [comment]
No problem, thank you for creating it. I did not know the addon wasn't maintainded. It works very well with the updated assets and is the only way I can play PSP games on Kodi. The PPSSPP core for RetroArch is crashing and is very slow.

Thank you for the quick responses.
