### ISSUE TITLE
Instructions inclear

### ISSUE THREAD

**Issue by axelsimon** [bite-your-idols/Gamestarter#152]
Hi,
The readme says cryptic things such as "you can download full Lakka core package" and "you should download AEL assets using RA's addon settings". Are these supposed to be understandable by newcomers who just want dump some ROMs in a directory and get a Kodi add-on to play them?

Another issue is that while Gamestarter makes it simple to install various frontends / game integration add-ons in Kodi (and thanks for that), the documentation doesn't make it clear whether one needs to install all of them, some of them, or just one of them.

I would suggest adding some numbered steps to the README to help people know what to do:
1. Install repository:
  1.1 Enable "unknown sources"
  1.2 etc.
  1.3 etc.
2. Install one of the following add-ons:
  2.1 etc.

Lastly, both EmulationStation and RetroArch installed via Gamestarter on CoreElec do nothing: launching them just exits Kodi and then reloads Kodi. That should probably be a separate issue though.

In any case, thanks, this effort seems to be the closest we have to offering a somewhat sane experience getting retro gaming to work on Kodi, which is currently ridiculously complicated compared to, say, adding films or even using Spotify.

**Comment by juanitopons** [comment]
Happenning to me the same.
I tried with older version of retroarch and get installed 2 version lower then the actual default one.

Try it. I'll investigate what's happening with new version because i would like to update.

**Comment by axelsimon** [comment]
This was closed with no explanation or answer :/

Can we work on an improved version of the README, that would be more helpful to newcomers?

Happy to help, we can start a CodiMD pad or something.
