### ISSUE TITLE
RetroArch not installed correctly on Raspbian Kodi

### ISSUE THREAD

**Issue by fvisagie** [bite-your-idols/Gamestarter#155]
Hi, thanks for the great work!

On Raspbian Kodi RetroArch is installed in a way that prevents it from running properly. At least part of the problem seems to be with how its paths are configured.

When launching RetroArch for setting up, the screen goes blank and nothing else happens. If I press Esc after a while I am returned to Kodi and when I exit Kodi itself, the console displays these RetroArch error messages:
![retroarch errors](https://user-images.githubusercontent.com/7724369/80408241-c811e080-88be-11ea-8b7a-26178f18fe18.png)

They seem to indicate that RetroArch is using incorrect path references. E.g. on Raspbian the Kodi userdata folders are at /home/\<user\>/.kodi, while RetroArch uses /storage/.kodi as the top-level folders.

Versions: Raspberry Pi 3B, Raspbian Stretch fully updated, Kodi 18.2, Gamestarter RetroArch 9.185.19.

I'd be really grateful for any help getting RetroArch to run! Let me know if there's anything else you need, thanks.

**Comment by bite-your-idols** [comment]
This RetroArch addon is compiled to work in LibreELEC distro, so only thing you can do is trying to edit this file: https://github.com/bite-your-idols/Gamestarter/blob/master/repository.gamestarter/game.retroarch/addon.start

**Comment by fvisagie** [comment]
I'm not hopeful about finding the time to have a go, but thanks for the pointer nonetheless.
