### ISSUE TITLE
Crashes when I do basically anything

### ISSUE THREAD

**Issue by mcplayer9999** [bite-your-idols/Gamestarter#157]
As the title suggests, the Retroarch addon (latest version) crashes when I do pretty much anything aside from idle on the first screen. My software and hardware are as follows:
LibreELEC 9.2
Ryzen 3 3200G+Vega 8 iGPU
8 GB DDR4
256 gig SSD and a 2 TB hard drive (for roms), and a 4 TB hard drive (for media)

Steps to reproduce:
1. Install the repo
2. Install the addon via the addon browser
3. Launch the addon
4. Start doing anything (loading a core, changing settings, etc.)

EDIT: the default Ozone menu was what caused the crashes after doing further research, if anyone else experiences this, SSH into your LibreELEC box and cd to .config/retroarch, edit retroarch.cfg, find "ozone" and replace with xmb (or anything other than ozone)

**Comment by bite-your-idols** [comment]
https://github.com/libretro/Lakka-LibreELEC/issues/793
