### ISSUE TITLE
Pls add support for Rockpro64 SBC

### ISSUE THREAD

**Issue by murrayf** [bite-your-idols/Gamestarter#158]
Hello, 

  I could sucessfully try retroarch on my intel x86_64 nuc, but when I try in my pine rockpro64 sbc there is a crash after loading retroarch and emulation station and kodi restarts...
  So it could be possible to make gamestarter works in this kind of machines?
Thanks and congratulations for gamestarter,
Alberto.
:)

**Comment by bite-your-idols** [comment]
Just for RPi and Generic devices, these are the only devices I own so I can test the builds.
