### ISSUE TITLE
Retroarch crash on start on LibreELEC 

### ISSUE THREAD

**Issue by KAW0** [bite-your-idols/Gamestarter#161]
RASPBERRY PI 4B
LibreELEC  9.2.3

![obraz](https://user-images.githubusercontent.com/16373327/89350078-9a071e00-d6af-11ea-8398-c0e22eb70626.png)

**Comment by Philps** [comment]
RA works for me. New install RASPBERRY PI 4B LibreELEC 9.2.6
But see: https://github.com/libretro/Lakka-LibreELEC/issues/793
