### ISSUE TITLE
RetroArch Crashes on LibreELEC 9.2.8/Kodi 18.9.0 on RPi4

### ISSUE THREAD

**Issue by CFTBL** [bite-your-idols/Gamestarter#165]
I've installed RetroArch under LibreELEC 9.2.8 (Kodi 18.9.0) via the Gamestarter 3.0.0 repository. In Kodi, when I launch the RetroArch add-on, it exits Kodi and runs RetroArch as it should. But then, if I click on anything in the RetroArch main menu (Information, Load Core, Configuration File, etc), RetroArch crashes and drops back to Kodi. Here's my RetroArch debug log. It aborts at the end with a message that is somewhat cryptic to me, but probably makes sense to someone. Any ideas?

[INFO] RetroArch 1.8.6 (Git 36802f7133)
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: May 14 2020
[INFO] Version: 1.8.6
[INFO] Git: 36802f7133
[INFO] =================================================
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/storage/emulators/saves/.srm".
[INFO] Redirecting save state to "/storage/emulators/saves/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ 960x720
[WARN] [DRM]: Couldn't get device resources.
[WARN] [DRM]: Couldn't get device resources.
[INFO] [DRM]: Found 1 connectors.
[INFO] [DRM]: Connector 0 connected: yes
[INFO] [DRM]: Connector 0 has 20 modes.
[INFO] [DRM]: Connector 0 assigned to monitor index: #1.
[INFO] [DRM]: Mode 0: (1920x1200) 1920 x 1200, 60 Hz
[INFO] [DRM]: Mode 1: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 2: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 3: (1600x1200) 1600 x 1200, 60 Hz
[INFO] [DRM]: Mode 4: (1680x1050) 1680 x 1050, 60 Hz
[INFO] [DRM]: Mode 5: (1280x1024) 1280 x 1024, 75 Hz
[INFO] [DRM]: Mode 6: (1280x1024) 1280 x 1024, 60 Hz
[INFO] [DRM]: Mode 7: (1152x864) 1152 x 864, 75 Hz
[INFO] [DRM]: Mode 8: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 9: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 10: (1024x768) 1024 x 768, 75 Hz
[INFO] [DRM]: Mode 11: (1024x768) 1024 x 768, 60 Hz
[INFO] [DRM]: Mode 12: (800x600) 800 x 600, 75 Hz
[INFO] [DRM]: Mode 13: (800x600) 800 x 600, 60 Hz
[INFO] [DRM]: Mode 14: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 15: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 16: (640x480) 640 x 480, 75 Hz
[INFO] [DRM]: Mode 17: (640x480) 640 x 480, 60 Hz
[INFO] [DRM]: Mode 18: (640x480) 640 x 480, 60 Hz
[INFO] [DRM]: Mode 19: (720x400) 720 x 400, 70 Hz
[INFO] [GL]: Found GL context: kms
[INFO] [GL]: Detecting screen resolution 1920x1200.
[INFO] [EGL] Found EGL_EXT_platform_base, trying eglGetPlatformDisplayEXT
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x1f6c428.
[INFO] [KMS]: New FB: 1920x1200 (stride: 7680).
[INFO] [GL]: Vendor: Broadcom, Renderer: V3D 4.2.
[INFO] [GL]: Version: OpenGL ES 3.0 Mesa 19.1.7.
[INFO] [GL]: Using resolution 1920x1200
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Font]: Using font rendering backend: bitmap.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: Keyboard #0 (/dev/input/event4).
[INFO] [udev]: Keyboard #1 (/dev/input/event0).
[INFO] [udev]: Mouse #0 (/dev/input/event5).
[INFO] [udev]: Mouse #1 (/dev/input/mouse1).
[INFO] [udev]: Mouse #2 (/dev/input/event1).
[INFO] [udev]: Mouse #3 (/dev/input/mouse0).
[INFO] [udev]: Plugged pad: Microsoft X-Box 360 pad (1118:654) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event6) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event6) supports 16 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [Video]: Found display server: null
[INFO] [ALSA]: Using signed 16-bit format.
[INFO] [ALSA]: Period size: 768 frames
[INFO] [ALSA]: Buffer size: 3072 frames
[INFO] [ALSA]: Can pause: no.
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Menu]: Found menu display driver: "gl".
[CDROM] No sg devices found and sg kernel module is not loaded.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x4b9710
[INFO] [MIDI]: Initializing ...
ALSA lib /var/lib/jenkins/LE/build4/workspace/RPi4/LibreELEC.tv/build.LibreELEC-RPi4.arm-9.2.8/alsa-lib-1.1.9/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
[ERROR] [MIDI]: snd_seq_open failed with error -2.
[ERROR] [MIDI]: Initialization failed (list of input devices unavailable).
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/storage/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
[INFO] Loading favorites file: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] [GL]: VSync => on
[INFO] [GL]: VSync => on
[INFO] [KMS]: New FB: 1920x1200 (stride: 7680).
[INFO] [KMS]: New FB: 1920x1200 (stride: 7680).
[CDROM] No sg devices found and sg kernel module is not loaded.
game.retroarch-RPi: ../src/broadcom/cle/v3d_packet_helpers.h:74: __gen_uint: Assertion `v <= max' failed.
Aborted

**Comment by CFTBL** [comment]
I found a workaround. If I use the clunky old RetroArch menu instead of the new one, it doesn't crash. You can use the old menu by going into /storage/.config/retroarch/retroarch.cfg and changing menu_driver = "ozone" to menu_driver = "xmb". I guess something is broken related to the ozone menu.

**Comment by bite-your-idols** [comment]
https://github.com/libretro/Lakka-LibreELEC/issues/793
