### ISSUE TITLE
gampad config for fba/mame

### ISSUE THREAD

**Issue by Roughtrade** [bite-your-idols/gamestarter#4]
Sorry,
one more Question; where i should i place a custom config for fba or mame. I cant start games ( insert coin -start )

regards Peter

**Comment by bite-your-idols** [comment]
Try in settings menu, quick menu, and search for core input configs, there you can remap your controller just for that core. Not all cores have this feature but most of them does. 

Also you can edit your controller config file and reasign buttons for all the emulator. It can be done both using settings menu> input or manually editing your file placed in "/storage/emulators/retroarch/configs/joypads/name_of_your_gamepad.cfg"
