### ISSUE TITLE
No sound on LibreELEC _x64

### ISSUE THREAD

**Issue by kalluxus** [bite-your-idols/Gamestarter#67]
Hi,

first of all thank you so much for this great addon!!! It was what I was looking for, for what feels like an eternety now. :)

However there's a little problem with the sound - it does not work on my machine.

I have LibreELEC v. 8.0.2 and the current Gamestarter release on an old ThinkPad which I mistreat as a media player ;)
Sound works fine in Kodi, turns off as soon as RetroArch starts and comes back on when Kodi is back.

What setting am I missing? The command from Issue #39 didn't help me because I got 
`amixer: Control hw:0 element write error: Operation not permitted`

Here's my audio device info:
`LibreELEC:~ # aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
Subdevices: 0/1
Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
Subdevices: 1/1
Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
Subdevices: 1/1`

Any idea what the problem might be?

Thanks a bunch!

**Comment by bite-your-idols** [comment]
did you try other workarounds from that issue? (specially the ones related with config.txt but using your needed parameters)

you can activate debugging in RetroArch and launch a rom, then copy/paste gamestarter_retroarch.log, maybe we can see some error or warning.

Also, you can try to uncomment lines 28 (modprobe snd_bcm2835) and 103 (rmmod snd_bcm2835) in /storage/.kodi/addons/script.gamestarter/resources/bin/gamestarter.start

**Comment by kalluxus** [comment]
Hi!
Thanks for your quick reply!
The solution was to be found somewhere else, though.

I had to enter the audio_device manually in retroarch.cfg as described here:
[https://github.com/libretro/Lakka-LibreELEC/wiki/Audio-settings](url)

Now it works. Sorry for all the fuss and thanks again for this amazing addon! :)
