### ISSUE TITLE
Retroarch doesnt start with LibreELEC-RPi2.arm-9.0-Milhouse-20170811210530-#0811

### ISSUE THREAD

**Issue by antaril** [bite-your-idols/Gamestarter#69]
Hi there,

i cant start Retroarch. Libreelec just reboots! WHat can i do? Emulation station starts good, but i cant launch any game...

log: /storage/.kodi/addons/game.retroarch/game.retroarch-RPi: error while loading shared libraries: libass.so.5: cannot open shared object file: No such file or directory

**Comment by bite-your-idols** [comment]
RetroArch in LE9 for RPi needs additional library you can download from here: https://github.com/bite-your-idols/Gamestarter/raw/master/packages/retroarch-LE9alpha-lib.7z
Then paste unzipped lib folder into game.retroarch folder.
You need to do this everytime you update RetroArch add-on.
