### ISSUE TITLE
Installation of plugins fail

### ISSUE THREAD

**Issue by lilbud** [bite-your-idols/Gamestarter#70]
I am running Kodi 17.3 on the Raspberry Pi 3. Everytime I try to install a plugin using Gamestarter, the installation fails after a few seconds.

**Comment by bite-your-idols** [comment]
Kodi 17.3 under libreELEC?

**Comment by lilbud** [comment]
It's actually Kodi 17.3 running on OSMC, would that be a problem?

**Comment by bite-your-idols** [comment]
Yes, this is just for LibreELEC.

**Comment by lilbud** [comment]
What is the difference between the two?

**Comment by bite-your-idols** [comment]
Try both and compare yourself.

https://duckduckgo.com/?q=libreelec+vs+osmc&atb=v67-6__&t=cros&ia=web

**Comment by lilbud** [comment]
Okay, I got LibreELEC setup, and I installed both Retroarch and Advanced Emulator Launcher. So where is Retroarch installed?

I'm trying to setup AEL, but can't due to not knowing where RA is installed.

**Comment by bite-your-idols** [comment]
If you install AEL from Gamestarter repo you just need to move categories.xml file from /storage/.kodi/addons/plugin.program.advanced.emulator.launcher/ to /storage/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher/ and you will get default launchers created for gamestarter installation. You an edit those created launchers to point to your roms folder instead default one or change default cores.

If you want to create it from scratch you can take a look to[ that file](https://github.com/bite-your-idols/Gamestarter/blob/master/repository.gamestarter/plugin.program.advanced.emulator.launcher/categories.xml) where you can find out how lo launch retroarch
