### ISSUE TITLE
[Request] Add option to change emulator in ES

### ISSUE THREAD

**Issue by askotx** [bite-your-idols/Gamestarter#74]
Is it posible to add this feature in metadata tags in gamelist.xml like recalbox? This is particularly useful when a game doesn't work in one core but works in other.

**Comment by bite-your-idols** [comment]
It is possible, I think so. I have this one in my road-map but now I am working on AEL prefect integration. Next will come ES. 
ES is not compiled by myself and all settings are hard-coded so my workaround is to edit system.cfg file from addon setttings in kodi. It would be nice that users can edit core/emulation per system and also the path to their rom folders.
I think it is possible but I don't know if I will achieve it.

In the meantime I supose you know you can edit manually (ssh or copy/paste to a PC) /storage/.kodi/userdata/addon_data/game.emulationstation/es_systems.cfg, do you?

**Comment by askotx** [comment]
Yeah, I know how to edit, but which tag should I add/edit to es_systems.cfg for specific core? I thought you compiled ES by yourself, I guess its harder than I was thinking.
Could a tag be sent to gamestarter.start to be used?

**Comment by bite-your-idols** [comment]
Compiling ES for LibreELEC is a little tricky so I grab from [Escalde's build](https://github.com/escalade/LibreELEC.tv).

when eidting es_systems.cfg you will find code blocks for each system/core/console like this:
`<system>
		<name>mame</name>
		<fullname>MAME</fullname>
		<path>/storage/emulators/roms/mame</path>
		<extension>.zip .ZIP</extension>
		<command>/storage/.kodi/addons/game.retroarch/addon.start mame2003 %ROM% ES</command>
		<platform>arcade</platform>
	</system>`

There you can replace path for your roms location (default is /storage/emulators/roms) and you can replace the core for each one, you just need to replace libretro core name in command tag.

example: replace mame2003_libretro core by mame2010_libretro core.
`<system>
		<name>mame</name>
		<fullname>MAME</fullname>
		<path>/storage/emulators/roms/mame</path>
		<extension>.zip .ZIP</extension>
		<command>/storage/.kodi/addons/game.retroarch/addon.start mame2010 %ROM% ES</command>
		<platform>arcade</platform>
	</system>`

**Comment by askotx** [comment]
Ok, it will work for replace full core to another, but if I only need one rom that works better with another core and leave main core for the rest of roms, is there a way to do it?

**Comment by bite-your-idols** [comment]
only way I can figure out is by creating a rom folder just for that rom/emulator and duplicate the code block for the system, letting one as default and the new one pointing to the new rom folder with the new core.

**Comment by askotx** [comment]
That's a way to solve it, but I think I should wait to a more elegant mode to solve it, could I leave this issue open until it's fixed?

**Comment by bite-your-idols** [comment]
I think this is not going to be "fixed" just because of what I said before, emulationstation is not compiled by myself... A lot of people using RetroPie do what I tell you in prev message (duplicate systems/folders) in order to achive what you want, so I think it can be a valid workaround. 

Also since you are using LibreELEC I recommend you to try Advanced Emulator Launcher because it is more powerful than ES and has a lot of customizable settings/options.

**Comment by askotx** [comment]
Ok, I' ll do your workaround, in any case there will just a few roms.
Thanks!!
