### ISSUE TITLE
LibreELEC 8.1 EmulationStation does not start up

### ISSUE THREAD

**Issue by karoljoc** [bite-your-idols/Gamestarter#75]
Hi,

Firstly thank you for the addons.  

I download the official release of LibreELEC 8.1.0 and installed your 3.0.0 gamestarter repo. I have EmulationStation 0.0.7 and RetroArch 8.164.1 installed, 

When I launch the EmulationStation the ES splash screen shows up for a few seconds and then goes back to Kodi splash screen. Not sure what the problem could be.

**Comment by bite-your-idols** [comment]
We need emulationstation.log and emulationstation_debug.log that are located in /storage/.kodi/temp

**Comment by karoljoc** [comment]
[Logfiles.zip](https://github.com/bite-your-idols/Gamestarter/files/1231945/Logfiles.zip)

**Comment by bite-your-idols** [comment]
Ok, lib missing. I will upload a zip with all libs later.

**Comment by karoljoc** [comment]
Thank you.

**Comment by bite-your-idols** [comment]
Download [this file](https://github.com/bite-your-idols/Gamestarter/raw/master/packages/emulationstation-Gen-lib.7z), unzip and paste all *.so files in /storage/.kodi/addons/game.emulationstation/lib (or lib-Gen if you don't run it for the first time). These are the whole required libs for ES in Generic x86_64, so it should work.

If you can, please ssh this command:
`ldd /storage/.kodi/addons/game.emulationstation/game.emulationstation-Gen`

and paste here the output.

Let's see if we can discover which .so files are required and which aren't, so we can delete some of them.

**Comment by karoljoc** [comment]
The emulator is starting up now, thank you :) 

Here is the results:

`
HTPC:~/.kodi/addons/game.emulationstation/lib # ldd /storage/.kodi/addons/game.emulationstation/game.emulationstation-Gen
        linux-vdso.so.1 (0x00007ffda13e1000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fcd01631000)
        libboost_system.so.1.63.0 => /storage/.kodi/addons/game.emulationstation/lib/libboost_system.so.1.63.0 (0x00007fcd01be4000)
        libboost_filesystem.so.1.63.0 => /storage/.kodi/addons/game.emulationstation/lib/libboost_filesystem.so.1.63.0 (0x00007fcd01bca000)
        libboost_locale.so.1.63.0 => /storage/.kodi/addons/game.emulationstation/lib/libboost_locale.so.1.63.0 (0x00007fcd01b39000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007fcd01aa7000)
        libfreeimage.so.3 => /storage/.kodi/addons/game.emulationstation/lib/libfreeimage.so.3 (0x00007fcd00fc7000)
        libSDL2-2.0.so.1 => /storage/.kodi/addons/game.emulationstation/lib/libSDL2-2.0.so.1 (0x00007fcd00eaa000)
        libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007fcd00c43000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0x00007fcd01a22000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fcd008c3000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fcd005bf000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fcd003a8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fcd019c9000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007fcd001a0000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fccfff83000)
        libboost_thread.so.1.63.0 => /storage/.kodi/addons/game.emulationstation/lib/libboost_thread.so.1.63.0 (0x00007fcd01a00000)
        libboost_chrono.so.1.63.0 => /storage/.kodi/addons/game.emulationstation/lib/libboost_chrono.so.1.63.0 (0x00007fcd019fb000)
        libicudata.so.57 => /storage/.kodi/addons/game.emulationstation/lib/libicudata.so.57 (0x00007fccfe706000)
        libicui18n.so.57 => /storage/.kodi/addons/game.emulationstation/lib/libicui18n.so.57 (0x00007fccfe498000)
        libicuuc.so.57 => /storage/.kodi/addons/game.emulationstation/lib/libicuuc.so.57 (0x00007fccfe2f4000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007fccfe0e7000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007fccfe0d3000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fccfdecf000)
        libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007fccfde5b000)
        libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00007fccfdbe7000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007fccfdbc5000)
        libglapi.so.0 => /usr/lib/libglapi.so.0 (0x00007fccfdb95000)
        libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007fcd019f4000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007fccfd985000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fccfd85a000)
        libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007fccfd84b000)
        libboost_atomic.so.1.63.0 => /storage/.kodi/addons/game.emulationstation/lib/libboost_atomic.so.1.63.0 (0x00007fcd019f1000)
`

**Comment by bite-your-idols** [comment]
Can you please update to latest ES addon v0.0.8 and tell me if it works? It should do, but I can not test it by myself.

**Comment by bite-your-idols** [comment]
Tested here: https://forum.libreelec.tv/thread/287-gamestarter-retrogaming-add-ons-rpi-generic/?postID=59823#post59823
