### ISSUE TITLE
RetroArch does not work

### ISSUE THREAD

**Issue by drrak** [bite-your-idols/Gamestarter#77]
_Google translator:_
After the last update (8.167.3) can not run RetroArch. Loading stops on screen with RetroArch graphics.

RPi3, LE 8.0.2

**Comment by bite-your-idols** [comment]
Yes, my error, I messed up with endlines after cleaning my local github folder...
Try again to install the same version, I checked it out and now it works for me.
sorry.

**Comment by drrak** [comment]
Now it is ok.

Thanks.
