### ISSUE TITLE
No Sound - ALSA Failed to initialise

### ISSUE THREAD

**Issue by AlanSmithe** [bite-your-idols/Gamestarter#79]
Hi, 
I've been looking for an answer but I can't find a similar situation.

Here is a part of the log where I think the error is described.

`
ALSA lib /home/chewitt/LibreELEC.82-images/build.LibreELEC-Generic.x86_64-8.1.1/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM 
[ERROR] [ALSA]: Failed to initialize...
[ERROR] Failed to initialize audio driver. Will continue without audio.
".RROR] [DSP]: Failed to initialize DSP filter "
`

I hope you can help me..

**Comment by AlanSmithe** [comment]
I tried this:

mount -o remount,rw /flash
nano /flash/config.txt
`
dtparam=audio=on

hdmi_force_edid_audio=1
hdmi_group=1
hdmi_mode=16
`
That didn't work 
aplay -l 
gives me this as output
`
Kodi1:~ # aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 0: ALC283 Analog [ALC283 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`
In Kodi this is my audio device " ALSA: HDA Intel, ONK TX-NR545 on HDMI#1"

Kodi1:~/.config # retroarch --features
-sh: retroarch: not found

Does this help?

**Comment by bite-your-idols** [comment]
I think you should edit your retroarch.cfg file (/storage/.kodi/userdata_addon_data/game.retroarch/retroarch.cfg) and edit this line:
`audio_device = ""`

You can try using values from your aplay -l output such as (card,device):
`audio_device = "0,3"`
`audio_device = "0,7"`
`audio_device = "0,8"`
`audio_device = "0,9"`
`audio_device = "0,10"`
or 
`audio_device = "1,0"`

**Comment by AlanSmithe** [comment]
Jup that did it. Thnx a million
