### ISSUE TITLE
Emulationstation error

### ISSUE THREAD

**Issue by nikklas** [bite-your-idols/Gamestarter#81]
Hi

When I'm starting a snes game in emulationstation, the game doesn't open and then back to main screen emulationstation. Some logs,

02:00:25.113 T:1962606592 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
02:00:25.737 T:1874850720   ERROR: GetDirectory - Error getting
02:00:25.859 T:1962606592   ERROR: Previous line repeats 6 times.
02:00:25.860 T:1962606592  NOTICE: initialize done
02:00:25.860 T:1962606592  NOTICE: Running the application...
02:00:25.901 T:1962606592  NOTICE: starting zeroconf publishing
02:00:25.902 T:1962606592  NOTICE: CWebServer[8080]: Started
02:00:25.903 T:1962606592  NOTICE: starting upnp client
02:00:25.913 T:1675621280  NOTICE: ES: Starting UDP Event server on port 9777
02:00:25.914 T:1675621280  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
02:00:26.795 T:1759507360 WARNING: CSkinInfo: failed to load skin settings
02:00:27.655 T:1751118752  NOTICE: Indigo NOTICE: STARTING Indigo SERVICE
02:00:34.365 T:1822421920  NOTICE: Register - new joystick device registered on addon->peripheral.joystick/0: PLAYSTATION(R)3 Controller
02:00:44.597 T:1767895968   ERROR: GetDirectory - Error getting
02:01:57.800 T:1564472224   ERROR: Previous line repeats 2 times.
02:01:57.800 T:1564472224   ERROR: AEL WARN : SingleInstance::__enter__() Lock in use. Aborting AEL execution
02:02:07.995 T:1962606592   ERROR: Previous line repeats 2 times.
02:02:07.996 T:1962606592   ERROR: GetDirectory - Error getting plugin://plugin.program.advanced.emulator.launcher/?com=SHOW_OFFLINE_LAUNCHERS_ROOT
02:02:07.996 T:1962606592   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.advanced.emulator.launcher/?com=SHOW_OFFLINE_LAUNCHERS_ROOT) failed
02:02:13.540 T:1962606592   ERROR: Control 55 in window 10001 has been asked to focus, but it can't
02:02:16.136 T:1874850720  NOTICE: LoadJpeg: unable to load /storage/.kodi/addons/game.emulationstation/fanart.jpg
02:02:17.329 T:1962606592  NOTICE: Storing total System Uptime
02:02:17.330 T:1962606592  NOTICE: Saving settings
02:02:17.360 T:1962606592  NOTICE: Saving skin settings
02:02:17.365 T:1962606592  NOTICE: stop all
02:02:17.366 T:1962606592  NOTICE: stop player
02:02:17.366 T:1962606592  NOTICE: ES: Stopping event server
02:02:17.600 T:1962606592  NOTICE: stopping upnp
02:02:17.753 T:1962606592  NOTICE: stopping zeroconf publishing
02:02:17.763 T:1962606592  NOTICE: CWebServer[8080]: Stopped
02:02:18.024 T:1675621280  NOTICE: ES: UDP Event server stopped
02:02:18.083 T:1962606592  NOTICE: stop dvd detect media
02:02:18.712 T:1962606592  NOTICE: clean cached files!
02:02:18.912 T:1751118752  NOTICE: Indigo NOTICE: CLOSING INDIGO SERVICES
02:02:18.914 T:1962606592  NOTICE: closing down remote control service
02:02:18.915 T:1962606592  NOTICE: stopped
02:02:19.116 T:1962606592   ERROR: GetDirectory - Error getting plugin://game.emulationstation/
02:02:19.117 T:1962606592   ERROR: CGUIMediaWindow::GetDirectory(plugin://game.emulationstation/) failed
02:02:19.169 T:1962606592  NOTICE: destroy
02:02:19.170 T:1962606592  NOTICE: unload skin
02:02:19.359 T:1962606592  NOTICE: unload sections
02:02:19.380 T:1962606592  NOTICE: special://profile/ is mapped to: special://masterprofile/
02:02:19.387 T:1962606592  NOTICE: application stopped...

Please, can you help me? Thanks in advance.

**Comment by bite-your-idols** [comment]
Please provide retroarch and emulationstation log files located in /storage/.kodi/temp

If you launch the same rom with retroarch, does it work? Did you previously download the snes core emulationstation uses (default: snes9x2010)?

**Comment by nikklas** [comment]
Retroarch_debug log

[ERROR] RetroArch is built for dynamic libretro cores, but libretro_path is not set. Cannot continue.
[ERROR] Fatal error received in: "init_libretro_sym()"
[ERROR] This core requires a content file.


emulationstation_debug log

ConfigPath /storage/.config/emulationstation

Thanks,

**Comment by nikklas** [comment]
Solved, downloaded all libretro cores.
