### ISSUE TITLE
Problems with playstation 3 controller

### ISSUE THREAD

**Issue by nikklas** [bite-your-idols/Gamestarter#82]
Hi again, please apologize for the inconvenience.

System: Raspberry 2, (Libreelec 8.1.1)

I've problems with playstation 3 controller, doesn't working in emulationstation, when I get in a game, I can see in yellow, playstation 3 not configured. 

Some logs, 

[INFO] Loading dynamic libretro core from: "/storage/.kodi/userdata/addon_data/game.retroarch/cores/snes9x2010_libretro.so"
[INFO] [overrides] no core-specific overrides found at /storage/.config/retroarch/config/Snes9x 2010/Snes9x 2010.cfg.
[INFO] [overrides] no game-specific overrides found at /storage/.config/retroarch/config/Snes9x 2010/Super Mario World [Esp].cfg.
[INFO] Shaders: preset directory: /storage/.config/retroarch/shaders/presets
[INFO] Shaders: no game-specific preset found at /storage/.config/retroarch/shaders/presets/Snes9x 2010/Super Mario World [Esp].cgp.
[INFO] Shaders: no game-specific preset found at /storage/.config/retroarch/shaders/presets/Snes9x 2010/Super Mario World [Esp].glslp.
[INFO] Shaders: no core-specific preset found at /storage/.config/retroarch/shaders/presets/Snes9x 2010/Snes9x 2010.cgp.
[INFO] Shaders: no core-specific preset found at /storage/.config/retroarch/shaders/presets/Snes9x 2010/Snes9x 2010.glslp.
[INFO] Environ SET_VARIABLES.
[INFO] Environ SET_CONTROLLER_INFO.
[INFO] Controller port: 1
[INFO]    SNES Joypad (ID: 1)
[INFO]    SNES Mouse (ID: 2)
[INFO]    RetroPad (ID: 1)
[INFO] Controller port: 2
[INFO]    SNES Joypad (ID: 1)
[INFO]    SNES Mouse (ID: 2)
[INFO]    Multitap (ID: 257)
[INFO]    SuperScope (ID: 260)
[INFO]    Justifier (ID: 516)
[INFO]    Justifiers (ID: 772)
[INFO]    RetroPad (ID: 1)
[INFO] Remaps: remap directory: /storage/.config/retroarch/config/remaps
[INFO] Remaps: no game-specific remap found at /storage/.config/retroarch/config/remaps/Snes9x 2010/Super Mario World [Esp].rmp.
[INFO] Remaps: no core-specific remap found at /storage/.config/retroarch/config/remaps/Snes9x 2010/Snes9x 2010.rmp.
[INFO] Redirecting save file to "/storage/emulators/saves/Super Mario World [Esp].srm".
[INFO] Redirecting savestate to "/storage/emulators/saves/Super Mario World [Esp].state".
[INFO] Environ GET_OVERSCAN: 0
[INFO] Environ GET_LOG_INTERFACE.
[INFO] Environ SET_SUPPORT_ACHIEVEMENTS: yes.
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[libretro INFO] Frontend supports RGB565 - will use that instead of XRGB1555.
[INFO] Environ PERFORMANCE_LEVEL: 7.
[INFO] Loading content file: /storage/emulators/roms/snes/Super Mario World [Esp].smc.
[INFO] Did not find a valid content patch.
[INFO] CRC32: 0x417fb4df .
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "B"
[INFO] 	RetroPad, User 1, Button "Y (left)" => "Y"
[INFO] 	RetroPad, User 1, Button "Select" => "Select"
[INFO] 	RetroPad, User 1, Button "Start" => "Start"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, User 1, Button "A (right)" => "A"
[INFO] 	RetroPad, User 1, Button "X (up)" => "X"
[INFO] 	RetroPad, User 1, Button "L" => "L"
[INFO] 	RetroPad, User 1, Button "R" => "R"
[INFO] 	RetroPad, User 2, Button "B (bottom)" => "B"
[INFO] 	RetroPad, User 2, Button "Y (left)" => "Y"
[INFO] 	RetroPad, User 2, Button "Select" => "Select"
[INFO] 	RetroPad, User 2, Button "Start" => "Start"
[INFO] 	RetroPad, User 2, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, User 2, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, User 2, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, User 2, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, User 2, Button "A (right)" => "A"
[INFO] 	RetroPad, User 2, Button "X (up)" => "X"
[INFO] 	RetroPad, User 2, Button "L" => "L"
[INFO] 	RetroPad, User 2, Button "R" => "R"
[INFO] 	RetroPad, User 3, Button "B (bottom)" => "B"
[INFO] 	RetroPad, User 3, Button "Y (left)" => "Y"
[INFO] 	RetroPad, User 3, Button "Select" => "Select"
[INFO] 	RetroPad, User 3, Button "Start" => "Start"
[INFO] 	RetroPad, User 3, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, User 3, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, User 3, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, User 3, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, User 3, Button "A (right)" => "A"
[INFO] 	RetroPad, User 3, Button "X (up)" => "X"
[INFO] 	RetroPad, User 3, Button "L" => "L"
[INFO] 	RetroPad, User 3, Button "R" => "R"
[INFO] 	RetroPad, User 4, Button "B (bottom)" => "B"
[INFO] 	RetroPad, User 4, Button "Y (left)" => "Y"
[INFO] 	RetroPad, User 4, Button "Select" => "Select"
[INFO] 	RetroPad, User 4, Button "Start" => "Start"
[INFO] 	RetroPad, User 4, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, User 4, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, User 4, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, User 4, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, User 4, Button "A (right)" => "A"
[INFO] 	RetroPad, User 4, Button "X (up)" => "X"
[INFO] 	RetroPad, User 4, Button "L" => "L"
[INFO] 	RetroPad, User 4, Button "R" => "R"
[INFO] 	RetroPad, User 5, Button "B (bottom)" => "B"
[INFO] 	RetroPad, User 5, Button "Y (left)" => "Y"
[INFO] 	RetroPad, User 5, Button "Select" => "Select"
[INFO] 	RetroPad, User 5, Button "Start" => "Start"
[INFO] 	RetroPad, User 5, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, User 5, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, User 5, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, User 5, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, User 5, Button "A (right)" => "A"
[INFO] 	RetroPad, User 5, Button "X (up)" => "X"
[INFO] 	RetroPad, User 5, Button "L" => "L"
[INFO] 	RetroPad, User 5, Button "R" => "R"
[libretro INFO] No ROM file header found.
PPU.RenderSub = 0
PPU.FullClipping = 1
Settings.Transparency = 1
Settings.SpeedhackGameID = 7
PPU.SFXSpeedupHack = 0
coldata_update_screen = 0
[libretro INFO] "SUPER MARIOWORLD" [checksum ok] LoROM, 8Mbits, ROM+RAM+BAT, NTSC, SRAM:16Kbits, ID:____, CRC32:34E4D664
[INFO] Environ GET_VARIABLE snes9x_next_overclock:
[INFO] 	Disabled(10MHz)
[INFO] Environ SET_MEMORY_MAPS.
[INFO]    ndx flags  ptr          offset   start    select   disconn  len      addrspace
[INFO] CHEEVOS system RAM: 0x16bf9c8 131072
[INFO] CHEEVOS save RAM:   0x16df9d0 2048
[INFO] CHEEVOS video RAM:  0x16ff9d8 65536
[INFO] CHEEVOS RTC:        0x74c1e008 0
Failed to open /storage/emulators/saves/Super Mario World [Esp].srm: No such file or directory
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 31955.87 Hz.
[ERROR] [SoftFilter]: Did not find config: 
[ERROR] [Video]: Failed to load filter.
[INFO] [Video]: Video @ 897x672
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x1.
[INFO] [GL]: Found GL context: videocore
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
[INFO] [GL]: Version: OpenGL ES 2.0.
[WARN] [GL]: GLES implementation does not have BGRA8888 extension.
32-bit path will require conversion.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] Querying EGL extension: KHR_image => exists
[ERROR] Failed to create rendering backend: freetype.
Failed to open 
: No such file or directory
[ERROR] Failed to create rendering backend: stb.
[INFO] [Font]: Using font rendering backend: bitmap.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
**[WARN] [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?
[INFO] [udev]: Plugged pad: PLAYSTATION(R)3 Controller (2821:6091) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event0) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event0) supports 16 force feedback effects.
[INFO] [Autoconf]: 0 profiles found.
[INFO] [Autoconf]: no profiles found for PLAYSTATION(R)3 Controller (2821/6091).
[INFO] [Joypad]: Found joypad driver: "udev".**
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [ALSA]: Using signed 16-bit format.
[INFO] [ALSA]: Period size: 768 frames
[INFO] [ALSA]: Buffer size: 3072 frames
[INFO] [ALSA]: Can pause: no.
[ERROR] [DSP]: Failed to initialize DSP filter "
".
[INFO] [Menu]: Found menu display driver: "menu_display_gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] Loading history file: [/storage/.kodi/userdata/addon_data/game.retroarch/content_history.lpl].
[INFO] Loading history file: [
/content_favorites.lpl].
[INFO] Loading history file: [/storage/.kodi/userdata/addon_data/game.retroarch/content_music_history.lpl].
[INFO] Loading history file: [/storage/.kodi/userdata/addon_data/game.retroarch/content_video_history.lpl].
[INFO] Loading history file: [/storage/.kodi/userdata/addon_data/game.retroarch/content_image_history.lpl].
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)

Thanks is advance

**Comment by bite-your-idols** [comment]
when you say "Emulationstation" you mean in Emulationstation`s game lists or after launching a game using emualtionstation, so in retroarch.

After installing addons, you should launch retroarch addon in order to copy some config files, including joystick autoconfig files.

**Comment by nikklas** [comment]
After launching a game using emualtionstation. In retroarch, i've same problem in retroarch's options. I can't navigate with ps3 controller in retroarch options.

**Comment by nikklas** [comment]
ok, some advances, playstation 3 controller recognized, now I can move in retroarch menu. Using bluetooth doesn't works, using a cord works. Any ideas to works with bluetooth?

**Comment by bite-your-idols** [comment]
First, you should pair it to your RPi in libreelec settings.

**Comment by nikklas** [comment]
Done before, but doesn't work, I'll play with cord. Thanks!!
