### ISSUE TITLE
No addons work on RPi3 with Openelec

### ISSUE THREAD

**Issue by samsolid** [bite-your-idols/Gamestarter#83]
Hi,
first of all, thanks for your great effort in this project. Appreciate it very much!
Today I installed the most recent 3.0.0 version on my RPi 3 with Openelec 8.0.4. 
First I tried to install RetroArch. After I started it I could see the intial logo of the programm but then it seemed to crash and my Kodi just rebooted.
Same thing happened with Emulation Station. Also, I tried to install Advanced Emulator Launcher and managed to add a ROM to the Gamestarter Launcher. When I tried to play that ROM same thing as mentioned above happened. A black screen appeared and my Kodi just restarted.

Hope you could help me!

**Comment by samsolid** [comment]
Here is the log of the retroarch_debug file btw:
/storage/.kodi/addons/game.retroarch/game.retroarch-RPi: error while loading shared libraries: libass.so.5: cannot open shared object file: No such file or directory

**Comment by bite-your-idols** [comment]
This repo is for LibreELEC. Addons won't work in OpenELEC. You have to move to LibreELEC or use old all-in-one Gamestarter addon: https://github.com/bite-your-idols/Gamestarter/tree/master/repository.gamestarter/script.gamestarter

**Comment by samsolid** [comment]
Thanks for the reply! I installed LibreELEC and it works! Unfortunately I have another issue. At first it worked smoothly and I could play a super mario rom on SNES at a good framerate but without sound on Retroarch. I tried googling this issue and looking at your replies on past sound isses but it didnt seem to work (aplay -l command returned just null to me). 
Then I tried to install AEL and run the ROM through it and finally the sound worked! But unfortunately the sound is crackling and the games run very slow and are unplayable. I have no idea why! I have a RPi3 so I think it should be able to play at least SNES games with a decent speed and normal sound.

I can open a new thread if this issues doesnt fit in this one.

**Comment by bite-your-idols** [comment]
I think sound worked with AEL because you rebooted your pi, sometimes after retroarch installation reboot is needed in order to make sound work.

Snes games run smoothly and with perfect sound so try rebooting your pi, check your config.txt, try another rom/core... 

Are you in a fresh installation or an update from OpenELEC?

**Comment by samsolid** [comment]
Ive rebooted my Pi several times and tried different cores and I have a fresh LibreELEC installation. Found a solution now though. I enabled the "Threaded Video" option in the retroarch settings menu and it works smoothly now with a good sound!
