### ISSUE TITLE
artworks folder is missing

### ISSUE THREAD

**Issue by jkms** [bite-your-idols/Gamestarter#84]
I can see that the categories.xml file references the path `/storage/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher/artworks` and the relevant subdirectories, however that path doesn't exist. This causes the scraping process to fail when attempting to save fanart and covers.

Creating the relevant directories manually fixes the issue.

I would have expected these folders to be created automatically when I installed the addon?

I'm using:
- LibreELEC-RPi2.arm-8.0.2
- Latest version of Gamestarter installed via repo using [link in readme](https://goo.gl/m36qLT)

As an aside, everything is working great now. Excellent work guys (gals?).

**--John**

**Comment by bite-your-idols** [comment]
AEL's categories.xml structure is not ok, we have been working in a better way of AEL-retroarch integration that will come with upcoming AEL v0.9.7

**Comment by bite-your-idols** [comment]
AEL updated to 0.9.7-beta1 in repo and AEL instructions in readme.
More info about the release:
https://forum.kodi.tv/showthread.php?tid=287826&pid=2652765#pid2652765
