### ISSUE TITLE
[Libreelec+ODROID C2] Error on starting RetroArch

### ISSUE THREAD

**Issue by GodHunter** [bite-your-idols/Gamestarter#85]
After installing RetroArch from Repository and starting it i see the wallpaper of RetroArch, after that Kodi restarts. I get the following in error logs:

RetroArch [ADDON] :: Thu Oct 5 21:36:08 CEST 2017
============================================================
RetroArch [ADDON] :: RetroPlayer core found: *
RetroArch [ADDON] :: Total RetroPlayer cores: 1
RetroArch [ADDON] :: Kodi is ready.
RetroArch [ADDON] :: Odroid_C2.aarch64-8.1.2 - Thu Oct 5 21:36:12 CEST 2017
RetroArch [ADDON] :: Stop kodi...
RetroArch [ADDON] :: Launch Retroarch (Enable debugging and see process output in retroarch_debug.log)
RetroArch [ADDON] :: Restart kodi...

/storage/.kodi/addons/game.retroarch/addon.start: line 169: /storage/.kodi/addons/game.retroarch/game.retroarch-Odr: not found

**Comment by bite-your-idols** [comment]
as you can see in readme title:
Retrogaming Kodi add-ons for LibreELEC **(RPi2/3 & Generic x86_64)**
so, sorry, no Odroid support...
