### ISSUE TITLE
A bit confuse about indications for RPi2/3 & Generic x86_64

### ISSUE THREAD

**Issue by belinux** [bite-your-idols/Gamestarter#86]
I just checked releases page, saw v3.0 description "kodi add-on repository for LibreELEC (RPi2/3 & Generic)" then lower a link for info about instalation which redirect to the readme where its making an exception for those who want the repo for RPi2/3 & Generic x86_64, whell I goto the link at it send me to v2.9.. now I am not sure which one is the right one..

**Comment by bite-your-idols** [comment]
Main repo readme is the latest, info about 3.0 repo.  The exception you see is:

> If you are looking for old Gamestarter addon please visit this link
So, if you are looking for old Gamestarter 2.9 all-in-one addon you must follow that link, if you want to use the v3.0 repo you should continue reading that readme.

I think it is so clear, old all-in-one version (v2.9 and below) is a complete addon including everything (AEL, RA, ES...). The new v3.0 is just a repo to install in kodi from where you can install and update one by one retrogaming addons you want.
