### ISSUE TITLE
Dualshock 4 not working on retroarch

### ISSUE THREAD

**Issue by rafaelhaertel** [bite-your-idols/Gamestarter#88]
So, yesterday i've installed retroarch on a rpi3 with librelec 8.0.2, connected my dualshock4 via bluetooth to navigate through kodi and opened retroarch and it worked out of the box without any additional configuration. Today i've did a fresh install in another sd card in the same rpi3 with the same configurations and when i open retroarch with the DS4 it doesn't work at all. It only works with my keyboard with the ds4 turned off. If i open with the ds4 and the keyboard it doesnt work either. But if open with the keyboard and then connect the DS4 it kinda works, but if i press any button it throttles a lot. 

Any thoughts?

Thank you

**Comment by bite-your-idols** [comment]
Bluetooth or USB? 
Check if autoconfig files have been copied correctly to /storage/.kodi/userdata/addon_data/game.retroarch folder or you can download/update them from within retroarch>online updater>autoconfig

Also you can connect online keyboard, go to retraroch settings>input settings> player 1 bindings and connect ds4 and remap all buttons.
