### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by vgoffman** [bite-your-idols/Gamestarter#89]
wont install on LibreELEC-RPi2.arm-8.2.1

**Comment by bite-your-idols** [comment]
Repo error? Retroarch error? Emulationstation error?...
LOGS??

**Comment by vgoffman** [comment]
I am installing from zip file on Raspberry Pi 3 using LibreELEC-RPi2.arm-8.2.1.img Fail installation

**Comment by vgoffman** [comment]
20:38:54.368 T:1737487264   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
20:38:54.368 T:1737487264   ERROR: CCurlFile::Open failed with code 0 for http://tv.eralim.com/repo/repository.gamestarter-3.0.0.zip
20:38:54.368 T:1737487264   ERROR: FileZip: unable to open zip file http://tv.eralim.com/repo/repository.gamestarter-3.0.0.zip!
20:38:54.369 T:1737487264   ERROR: Failed to unpack archive 'zip://http%3a%2f%2ftv.eralim.com%2frepo%2frepository.gamestarter-3.0.0.zip/repository.gamestarter/' to '/storage/.kodi/addons/temp/8f699177-2bac-4755-8b93-708b21fd0a12'

**Comment by vgoffman** [comment]
repository.gamestarter-3.0.0.zip including only 4 files: addon, changelog, fanart and icon

**Comment by bite-your-idols** [comment]
It seems something is wrong with your LibreELEC installation. Try downloading repo zip again and if error continues try to install it in a new nee fresh LE installation

**Comment by vgoffman** [comment]
Its new and clean LibreELEC installation

**Comment by bite-your-idols** [comment]
I've just tried again in a fresh new LE installation and it works like a charm.
Please make sure you have the correct zip file, that you have transfer to your pi correctly and that your LE internet connection is working.

**Comment by vgoffman** [comment]
can you give me a correct link for kodi repository?
