### ISSUE TITLE
Updating clarification

### ISSUE THREAD

**Issue by vobi1024** [bite-your-idols/Gamestarter#90]
Can You tell me please, what is the correct method for updating:
1. the Gamestarter add-on module
2. the cores installed in retroarch (atm I use only the retroarch module) 
    namely do I need to do it in retroarch 1 by 1 with the online core updater or can I use the install all cores in the Gamestarter module?
Thank You!

**Comment by bite-your-idols** [comment]
- install gamestarter repo
- install retroarch addon
- download lakka cores package using retroarch addon settings
- update retroarch when new addon update releases (this will not delete your previously downloaded cores)

**Comment by vobi1024** [comment]
Wow, thats fast answer, thank You!
"update retroarch when new addon update releases" - inside retroarch or outside retroarch with the reatroarch addon?

**Comment by bite-your-idols** [comment]
- update retroarch **addon** when new addon update releases (kodi will notify you or you can check for updates manually by using context menu when Gamestarter repo is selected).

**Comment by vobi1024** [comment]
thank You!
