### ISSUE TITLE
Issue importing configuration.

### ISSUE THREAD

**Issue by jameshope87** [bite-your-idols/Gamestarter#91]
I am trying to complete this step.in the readme:

After installing this addon you should download AEL assets using RA's addon settings. Then, go to AEL settings → I/O → Import category/launcher configuration... and select the systems you want to import one by one or select whole systems import config file (/storage/emulators/ael-assets/Gamestarter - Category assets.xml).

However when I press the "import category..." In AEL settings, there is nothing to choose from. No option to browse further either. Any ideas?

**Comment by TheCherry** [comment]
Have the same Issue. There is no "download AEL assets" option in RetroArch ... I can only download the cores and I did that.
