### ISSUE TITLE
RetroArch does not load

### ISSUE THREAD

**Issue by ArnoutVerbeken** [bite-your-idols/Gamestarter#92]
Hello,

Trying your addon on a Beelink MiniMX III box (S905X), but it does not start....  I see the splash screen but it immediately gets back to Kodi

I have the following in the debug log:
`/storage/.kodi/addons/game.retroarch/addon.start: line 169: /storage/.kodi/addons/game.retroarch/game.retroarch-S90: not found`

I checked that path and there is indeed no S90 file in there...

Any chance this can be solved?

Thanks

**Comment by bite-your-idols** [comment]
Sorry but just Raspberry Pi (2/3) and Generic x32_64 PCs are supported.

**Comment by ArnoutVerbeken** [comment]
Thanks.  For those with the same problem, you can try AlexElec on https://github.com/AlexELEC/AlexELEC-AML
