### ISSUE TITLE
RetroArch freeze?

### ISSUE THREAD

**Issue by diehumel** [bite-your-idols/Gamestarter#93]
Hello,

after starting RetroArch i'm not able to navigate (even with keyboard) in the menu and there is no effect within the menu (even the clock is not running).
[retroarch.log](https://github.com/bite-your-idols/Gamestarter/files/1583318/retroarch.log)
[retroarch_debug.log](https://github.com/bite-your-idols/Gamestarter/files/1583319/retroarch_debug.log)

Maybe it is noticeable that there is always a cursor, independent of the connected input device. I would have expected that the cursor only appears with a connected mouse.

My system:
Beebox N3000
LibreELEC 8.2.1 x86_64 
RetroArch 8.169.7 (from Gamestarter repository)
Tested input devices (working fine within kodi):
8BITDO SFC30 GAMEPAD (connected via USB)
Logitech K400r
Logitech G110
Harmony Remote with ASrock mappings

I already raised a topic in the libretro forum but because there is no effect or keyboard response this might be the correct location.
https://forums.libretro.com/t/input-devices-not-responding/13847

Thank you in advance

**Comment by bite-your-idols** [comment]
Disable all shaders and overlays and try to run retroarch just without any usb plugged. If it works try connecting your keyboard. If it doesnt you must consider to try in a fresh LibreELEC installation. 
Also you can try installing VNC addon in your device and VNC client in another device and see if you can control it.

**Comment by s6joui** [comment]
Hello, I have the same problem. I tried disconnecting all usb devices and a fresh installation but it still freezes when I launch retroarch.

**Comment by bite-your-idols** [comment]
What device? What LibreElec version?

**Comment by s6joui** [comment]
I'm running it on an old laptop. Intel Celeron T3000 with Intel Integrated Graphics GM45, LibreElec 8.2.5 and latest retroarch addon.

Here's the retroarch log. I don't see anything strange
> [INFO] [recording] twitch streaming key empty[INFO] RetroArch 1.7.5 (Git c9c6c5a)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3
Built: Oct  3 2018
[INFO] Version: 1.7.5
[INFO] Git: c9c6c5a
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/storage/emulators/saves/.srm".
[INFO] Redirecting savestate to "/storage/emulators/saves/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ 960x720
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [GLX]: Window manager is Fluxbox.
[INFO] [GLX]: X = 0, Y = 0, W = 960, H = 720.
[INFO] [GLX]: Found swap function: glXSwapIntervalMESA.
[INFO] [GLX]: glXSwapInterval(1)
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Mobile Intel® GM45 Express Chipset .
[INFO] [GL]: Version: 2.1 Mesa 17.1.3.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ...
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Resetting shader to defaults ...
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [udev]: Plugged pad: Generic X-Box pad (9414:22554) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event8) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event8) supports 16 force feedback effects.
[INFO] [Autoconf]: 187 profiles found.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: bitmap.
[INFO] [X11]: Suspending screensaver (X11, xdg-screensaver).
sh: xdg-screensaver: not found
[WARN] Could not suspend screen saver.
[INFO] [Video]: Found display server: x11
[INFO] [autoconf]: selected configuration: /storage/.config/retroarch/autoconfig/udev/Generic_X-Box_pad.cfg
[INFO] [ALSA]: Using signed 16-bit format.
[INFO] [ALSA]: Period size: 1024 frames
[INFO] [ALSA]: Buffer size: 3072 frames
[INFO] [ALSA]: Can pause: no.
[INFO] [Menu]: Found menu display driver: "menu_display_gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x83f260
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "null" driver.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/storage/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
[INFO] [GL]: VSync => on
[INFO] [GLX]: glXSwapInterval(1)
[INFO] [GL]: VSync => on
[INFO] [GLX]: glXSwapInterval(1)

**Comment by bite-your-idols** [comment]
Neither do I. I am sorry.
You can try installing this custom build:
https://forum.libreelec.tv/thread/12662-libreelec-9-0-reborn-remix-emulationstation-retroarch-dolphinqt-moonlight-chrome/?pageNo=1

**Comment by s6joui** [comment]
Hello, I was able to solve the problem by updating LibreElec to the latest version (v8.95.2 BETA)
Now everything works as it did with Lakka

**Comment by bite-your-idols** [comment]
Happy to hear that!
