### ISSUE TITLE
EmulationStation and RetroArch won't start

### ISSUE THREAD

**Issue by mrfixit3000** [bite-your-idols/Gamestarter#94]
I have successfully installed your gamestarter repository and then install both emulationstation and retroarch. Neither will launch. Attached are the logs.

The logs look like they are searching for files that don't exist, both ending in "-ROC" instead of the existing "-GEN" and "-RPi" files. Looks like the code you're using in your .start applications "(head -c 3 /etc/release)" is finding "ROC" since my platform is "ROCK64", and never checks if the value is RPi or Gen, so ROC is invalid.

So I tried manually starting the existing files over ssh...
When I connect to SSH and manually pause the kodi service and then try and run the existing files, these are the errors I see:
  ./game.emulationstation-Gen: line 1: syntax error: unexpected ")"
  ./game.emulationstation-RPi: error while loading shared libraries: libboost_system.so.1.63.0: cannot open shared object file: No such file or directory
  ./game.retroarch-RPi: error while loading shared libraries: libass.so.5: cannot open shared object file: No such file or directory
  ./game.retroarch-Gen: line 1: syntax error: unexpected ")"

I tried overriding the $PROJECT variable in your .start applications to both "Gen" and "RPi" so that the rest of the script runs the supporting code, but for "Gen" the ssh command returns "sed: bad option in substitution expression" and the debug file returns the same "unexpected ")" error as shown above, and for "RPi" there's no command error and the debug log shows "error while loading shared libraries: libbcm_host.so: cannot open shared object file: No such file or directory"

Is there a github for the supporting code behind these executables so I can do further testing and debug? I can compile these apps from source on my platform if so.
Or can you provide further assistance? 

The ROCK64 platform is relatively new, but I've been able to get RetroPie, RetroArch, and EmulationStation to all run under debian stretch on this board, so I'm confident these GameStarter apps will work as well with some slight tweaks. Looking forward to your reply, and I'll be sure to share any positive results in the forums. This platform is becoming very popular and is a great performance boost over the RPI3b and has the same form factor so it's very compatible, so I'm confident more and more people will want this!

[retroarch.log](https://github.com/bite-your-idols/Gamestarter/files/1670698/retroarch.log)
[retroarch_debug.log](https://github.com/bite-your-idols/Gamestarter/files/1670699/retroarch_debug.log)
[emulationstation.log](https://github.com/bite-your-idols/Gamestarter/files/1670700/emulationstation.log)
[emulationstation_debug.log](https://github.com/bite-your-idols/Gamestarter/files/1670701/emulationstation_debug.log)

**Comment by mrfixit3000** [comment]
I see a lot of previously closed issues for boards you don't support. Any chance I could assist in resolving this myself if you point me to a repository for the source for the addon, rather than just saying my platform isn't supported? ;)

**Comment by bite-your-idols** [comment]
I don't have a ROCK64 device, just my RPi and my laptop, so I can not test anything by myself... If you want to try to compile retroach and emualtionstation binaries using LibreELEC tootlchain and make them work we can figure out a way for other users with your device to get that version, but I can not include in my addon because if I want to make an addon update I can not wait until those version are ready.

**Comment by mrfixit3000** [comment]
I can provide the compiled binaries, there isn't a lot of magic there beyond adding support for the Mali gpu. The issue is that out of the box the binaries will search for the compiled supporting libraries in /usr/lib so they cannot be added after compiling libreelec. It appears you have modified your binaries to search for these libraries in a sub folder of your addon, which is awesome. If you can guide me thru how to do that then I can assist with the compiling.

**Comment by mrfixit3000** [comment]
Another thought is that there is a version of lakka that supports the ROCK64 now, so perhaps you could reference that binary and supporting libraries?

**Comment by bite-your-idols** [comment]
Kodi searches for libs into addons subfolders named lib, there is no magic in it XD.

You need to compile binaries using libreelec toolchain, in that way no additional libs will be needed. You can take a took to escalade's custom build.

Lakka' retroarch binary is not valid because it includes additional options and settings. What can be used from lakka is all core files. You will need to copy them to use them later in libreelec. But this can only be done using a rock64 device.

**Comment by mrfixit3000** [comment]
I've actually been trying to get escalade's build working correctly, it compiles fine but I run into problems launching due to SDL not initializing a window. But his binaries all use the standard library locations from what I can tell, they are not under an addon subfolder like yours are. And when we launch ES or RA from Kodi it stops the Kodi service and runs your binary, so how does your binary know that it's libraries are not located in the usr/lib folder?

**Comment by bite-your-idols** [comment]
If you compile standard libreelec and include retroach and emulationstation (with their required patches and dependencies) binaries don't need additional libs. 
In my latest addon versions I grab those binaries from escalade's build so I need to add also required libs.

When librelec boots it gets all libs inside lib subfolders and load them in memory so although you exit kodi they are still loaded.

**Comment by mrfixit3000** [comment]
If I compile standard libreelec and include ES and RA packages from escalate's build, a dependency includes properly configured SDL library. The ROCK64 uses GLES with the MALI driver. I've tried all the configuration settings for SDL compilation but no matter what I do ES and RA can't initialize. Your addons appear to include libraries (including SDL) in a subfolder of the addon, rather than utilize the libraries that KODI puts in memory. I just don't know how you get your binaries to use the libraries in these sub folders. If you're saying your addons use the libraries in memory, why are they included in the sub folders for your package?

**Comment by bite-your-idols** [comment]
If you compile LE from offcial release and include in the compilation toolchain RA and ES packages you will not need additional assets.

If you compile LE from escalade's build and you want to use its RA and ES binaries you will also need additional libs or dependencies because in those 2 builds are not the same and does not use the same libraries. You can use "ldd" command in order to find out which libs are required by each binary.

If you put lib files in to a lib subfolder inside an addon folder, at boot, libreelec will load them into memory as all libs in usr/lib folder.

First I used to compile RA by myself using official LE toolchain, so no additional libs where included, but in latest RA compilations I get some error that I don't know how to solve (I am no basj/linux programmer, just web developer) so I decided to grab that binary from escalade's build, thats why now my addon includes additional libs.

**Comment by mrfixit3000** [comment]
Last night I was able to compile a retroarch binary that successfully runs with LibreElec on the ROCK64. I used the package.mk file from the Lakka github source and made slight modifications so that it didn't run on boot. I first tested using escalade's kodi patch to add an "emulation" option to the menu that launches retroarch and stops the kodi service. I next tested by adding this binary as "game.retroarch-ROC" in the ~/.kodi/addons/game.retroarch folder so that your gamestarter app launches it. Working perfectly after pointing it to the correct assets folder.

[retroarch.zip](https://github.com/bite-your-idols/Gamestarter/files/1673456/retroarch.zip)

**Comment by mrfixit3000** [comment]
but... still no luck with ES. Currently stuck with this error, tried a number of different settings.

lvl0:      Error creating SDL window!
        Could not get EGL display
lvl0:   Renderer failed to initialize!
lvl0:   Window failed to initialize!

**Comment by bite-your-idols** [comment]
I never could compile ES...

**Comment by mrfixit3000** [comment]
Can you please expand on Your comment:
"If you compile LE from offcial release and include in the compilation toolchain RA and ES packages you will not need additional assets."
It makes it sound like the official release of LE includes RA and ES out of the box. Which last I checked it did not. What's different about making RA and ES run when compiling LE from official release versus compiling escalades build?

**Comment by bite-your-idols** [comment]
If you take a look to both of them you will see thay are different projects, with different settings, libraries, dependencies... 

Official LE does not include RA or ES, you need to clone the project and paste RA and ES packages from lakka, escalde or wherever, then include those binaries in compilation toolchain. Then, RA binary will need no additional library. As I said, I never get ES compiled in that way... but one more time, all I know about compiling has been teached by master escalade.

**Comment by mrfixit3000** [comment]
Yep, that's exactly how I thought it worked, but I appreciate you confirming that for me! 

With Retroarch compiled, now I can at least embed emulators into libreelec...Even tho at anything higher than the lowest resolution N64 performance is worse than on the RPi3, which has a fraction of the hardware power of the ROCK64. But I expect that's a driver / kernel bottleneck, with the platform being so new.  

I'll keep hammering at ES compile and try to get the kernel and driver's updated, but I'll close this issue out. If I get any further with ES I'll update.

**Comment by mrfixit3000** [comment]
As a follow-up, SDL2.0.8 allows ES to compile and run with the supporting GLES flags :)

**Comment by Eggg98** [comment]
> Last night I was able to compile a retroarch binary that successfully runs with LibreElec on the ROCK64. I used the package.mk file from the Lakka github source and made slight modifications so that it didn't run on boot. I first tested using escalade's kodi patch to add an "emulation" option to the menu that launches retroarch and stops the kodi service. I next tested by adding this binary as "game.retroarch-ROC" in the ~/.kodi/addons/game.retroarch folder so that your gamestarter app launches it. Working perfectly after pointing it to the correct assets folder.
> 
> [retroarch.zip](https://github.com/bite-your-idols/Gamestarter/files/1673456/retroarch.zip)

I know this is old, but i am trying to get this work and still cant make it work, Retroarch still wont launch :c i donwload the file and rename it game.retroarch-ROC, then put in /.kodi/addons/game.retroarch but nothing works :c

**Comment by Eggg98** [comment]
/storage/.kodi/addons/game.retroarch/game.retroarch-RK3: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory

I have to change the file name, but now i am getting this error :c i am a complete noob with this :c

**Comment by mrfixit2001** [comment]
@Eggg98 wow, 3 years ago, thanks for the memories! :) I ended up abandoning this build and ported recalbox to the rock64 instead, and then a bunch of other platforms. You can find that old port in my github repo. Sadly, the recalbox devs were not easy to work with, and I don't believe they ever added my port. These days I'd suggest batocera over recalbox any day! I also have a new project that's cooking, you can read about it at retro-cone.com. But recalbox, batocera, and the new project all include a ton of retro-gaming systems with emulationstation, and the ability to switch over to KODI (or boot right into it). So I'd suggest just going one of those routes

**Comment by Eggg98** [comment]
Thank you so much for the tips and for your work in those projects! I will check all that :D finally i will be able to use my ROCK64 how i wanted it :D Also amazing project  you got there in retro-cone.com, i will stay tune 👍

**Comment by mrfixit2001** [comment]
In case you want to join the retro-cone discord server and help me beta test :)

https://discord.gg/Ce6fbmyB

- Mr.FixIt
