### ISSUE TITLE
Cannot launch N64 games.

### ISSUE THREAD

**Issue by jameshope87** [bite-your-idols/Gamestarter#96]
When I try to launch N64 games from retroarch (or with emulation station) the game fails to load.

The retroarch_debug.log looks like this:

```
[INFO] Loading dynamic libretro core from: "/storage/.kodi/userdata/addon_data/game.retroarch/cores/mupen64plus_libretro.so"
[ERROR] Failed to open libretro core: "/storage/.kodi/userdata/addon_data/game.retroarch/cores/mupen64plus_libretro.so"
[ERROR] Error(s): libpng12.so.0: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)
```

It seems there is some missing file. I have tried loading with the parallel core and it loads but is very slow. How can I get the mupen core working or download a different emulator?

**Comment by bite-your-idols** [comment]
did you download mupen64 core within retroarch or using addon's lakka package?

**Comment by bite-your-idols** [comment]
cores that are downloaded within retroarch sometimes fails due to no optimization for RPi. If you use Lakka package all cores must work.

**Comment by jameshope87** [comment]
I am not running on RPi though. It is a normal PC.

I will try the Lakka package again. Does it download them somewhere different because it didn't seem to work before.

**Comment by bite-your-idols** [comment]
you can download cores you want from here:
https://github.com/bite-your-idols/Gamestarter/tree/master/packages/libretro-cores-Gen

**Comment by jameshope87** [comment]
Ok I will give that a go and report back.

**Comment by jameshope87** [comment]
Ok, so I downloaded the core from there and now it launches. However it is really slow! Like 2 or 3 frames per second.

Very odd as this is a more powerful machine than a RPi3.

**Comment by bite-your-idols** [comment]
Its not everything about power but core optimization or core settings...
Maybe with newer core builds they improve core performance... You should look for info about that in libretro or lakka forums...
