### ISSUE TITLE
only certain ds4's on bluetooth work

### ISSUE THREAD

**Issue by camatthew** [bite-your-idols/Gamestarter#98]
the other ones have daouble input problems

**Comment by bite-your-idols** [comment]
Do they work ok in kodi?

**Comment by camatthew** [comment]
Yes

**Comment by camatthew** [comment]
Im using a pi 3b onboard bluetooth

**Comment by bite-your-idols** [comment]
LibreElec version?

You can try to edit key/button assigment by launching retroarch with an usb keyboard and the non-working DS4, then go to settings and  create player 1 bindings pressing the buttons as it asks you.

**Comment by camatthew** [comment]
I have libreelec latest stable and the issue only applies to some controllers

**Comment by camatthew** [comment]
They work for the ps4 and they are the ones without the light on the touchpad

**Comment by bite-your-idols** [comment]
any news about this?
` you should do what I suggest in prev comment:
You can try to edit key/button assigment by launching retroarch with an usb keyboard and the non-working DS4, then go to settings and create player 1 bindings pressing the buttons as it asks you.`

**Comment by camatthew** [comment]
I no longer need help since im using a ds3 wired instead
