### ISSUE TITLE
RetroArch and EmulationStation won't start - LibreElectTV 8.2.3.1 (Amlogic S805)

### ISSUE THREAD

**Issue by Cereal-Killa** [bite-your-idols/Gamestarter#99]
Installed the latest version from your repo, when I try to launch any of the apps they will display the splash screen perfectly (retroarch and emulationstation) but after 10 seconds or so it will return to Kodi.

I tried a few older versions you have here for LE but on all of them either it closes from splash screen back to kodi or I get a spinning wheel that takes me back too.

From within the addon setup screen I can config and download stuff, the addon will configure itself too and I get the message that all I need now is to add the roms and that's where the rom launchers fail to work.

Any help is appreciated.

**Comment by bite-your-idols** [comment]
sorry just for Raspberry Pi 2/3 and Generic.x86_64 devices.

**Comment by Cereal-Killa** [comment]
Thanks, this is what I got working: https://mxqproject.com/scottelec-ultimate-retro-games-system-for-amlogic-devices/
